// Generated by scripts/compile-help-corpus.ts. DO NOT EDIT.
export const HELP_CORPUS_VERSION = "1.1.0+3e7bb5c484310f49" as const;
export const GENERATED_HELP_CATEGORIES = [
  "Getting started",
  "Your two identities",
  "Using AgoraNet",
  "Money, fees & treasury",
  "Privacy, safety & rules",
  "Troubleshooting"
] as const;
export const GENERATED_HELP_ARTICLES = [
  {
    "id": "help.economy.donations-treasury",
    "slug": "donations-treasury",
    "title": "Donations and the treasury",
    "category": "Money, fees & treasury",
    "categoryId": "economy",
    "summary": "Follow public flows and understand the difference between internal balances and test-rail transactions.",
    "body": [
      "The transparency surface shows published rails and treasury records. Current internal balances and test-rail assets are labeled honestly; one must not be mistaken for the other.",
      "For a transaction problem, preserve the public transaction hash and the exact time. Never send a seed phrase or signing key. Missing-value reports require human review."
    ],
    "keywords": [
      "donation",
      "treasury",
      "balance",
      "funds",
      "transaction",
      "dPOLL"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "economy-specs",
      "owners-guide"
    ],
    "documentType": "concept",
    "escalateWhen": "A confirmed transaction is absent from the platform, a balance changed unexpectedly, or compromise is suspected.",
    "links": [
      {
        "href": "/transparency",
        "label": "Transparency"
      },
      {
        "href": "/treasury",
        "label": "Treasury"
      }
    ]
  },
  {
    "id": "help.economy.money",
    "slug": "money",
    "title": "PollCoin, Gratium, and fees",
    "category": "Money, fees & treasury",
    "categoryId": "economy",
    "summary": "Two currencies, published rails, and an economy that cannot sell attention.",
    "body": [
      "The platform runs on two internal currencies: PollCoin (PC) and Gratium (G). New identities hatch with a grant of each, so nobody is born traceable by poverty and first actions are free.",
      "Fees and deposits are the platform's real throttle; they make floods expensive while a deliberating human never notices them. Every number is a rail: published, bounded, and poll-adjustable by the community. The full table lives on the transparency page; searching the help lane also surfaces individual rails.",
      "The economy cannot sell attention because it never captures attention: no views, no dwell time, no engagement metrics exist anywhere in the system."
    ],
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "economy-specs",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/transparency",
        "label": "Every rail, published"
      }
    ]
  },
  {
    "id": "help.getting-started.onboarding-interrupted",
    "slug": "onboarding-interrupted",
    "title": "Onboarding was interrupted",
    "category": "Getting started",
    "categoryId": "getting-started",
    "summary": "Return to the journey without sharing or recreating secrets unnecessarily.",
    "body": [
      "Return to the gate in the same browser. AgoraNet will carry forward any completed server-side stage and will never ask support to reconstruct a secret that was shown once.",
      "If you already created an identity and saved its access key, use Sign in instead of beginning again. If a one-time secret was shown but not saved, read the recovery-boundary article before taking another action."
    ],
    "keywords": [
      "onboarding stuck",
      "continue onboarding",
      "closed browser",
      "resume",
      "start over"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate",
      "credential",
      "identity",
      "alias",
      "values"
    ],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ],
    "documentType": "troubleshooting",
    "links": [
      {
        "href": "/verify",
        "label": "Resume onboarding"
      },
      {
        "href": "/login",
        "label": "Sign in"
      }
    ]
  },
  {
    "id": "help.getting-started.values-seed",
    "slug": "values-seed",
    "title": "The values seed and your first action",
    "category": "Getting started",
    "categoryId": "getting-started",
    "summary": "Seven small answers orient your experience; they are not a universal score.",
    "body": [
      "The values seed asks one question from each pillar. It gives your new identity a starting orientation and helps relevant parts of the commons become visible.",
      "It is not a test, personality label, or cross-profile score. Each identity has its own answers. Completing onboarding carries you back to the action that brought you to the gate."
    ],
    "keywords": [
      "values seed",
      "seven questions",
      "first action",
      "orientation"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ],
    "documentType": "concept"
  },
  {
    "id": "help.getting-started.verify-once",
    "slug": "verify-once",
    "title": "Verify once, act forever",
    "category": "Getting started",
    "categoryId": "getting-started",
    "summary": "Reading is free for everyone; acting requires proving you're one real human, once.",
    "body": [
      "Everything on AgoraNet can be read without an account; search, Discussions, the Public Record, poll results. Reading is free, forever, and nobody watches you do it.",
      "Acting; posting, voting, joining Circles; requires passing the gate once: the ceremony at /verify proves you are one real human and hands you a Humanity Credential. That credential is the root of everything else; the platform stores only a hash of it, so it is shown to you exactly once.",
      "From the credential you register your True Self: your signed public identity, with its own @handle and access key. The access key is how this browser signs that identity in; also shown once, also unrecoverable if lost. Save both somewhere real."
    ],
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [
      "gate"
    ],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/verify",
        "label": "The gate ceremony"
      },
      {
        "href": "/constitution",
        "label": "The constitution"
      }
    ]
  },
  {
    "id": "help.getting-started.what-to-save",
    "slug": "what-to-save",
    "title": "Your two codes; what to save, and what loss means",
    "category": "Getting started",
    "categoryId": "getting-started",
    "summary": "The Humanity Credential and each identity's access key are shown once and never recoverable.",
    "body": [
      "The platform never stores your secrets in a readable form; only hashes. That is a feature: nobody can take from the platform what the platform does not hold. The cost is honest and permanent: a lost secret is gone.",
      "You hold two kinds of secret. Your Humanity Credential is the passport; it proves one-real-human at ceremonies like hatching an Alias. Each identity's access key is a house key; it signs that identity into a browser.",
      "Losing an access key means that identity can never be signed in anywhere new. Losing the credential means no new ceremonies; though identities already signed in keep working. Write them down somewhere real the moment they are shown."
    ],
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ],
    "documentType": "concept"
  },
  {
    "id": "help.identities.lost-keys",
    "slug": "lost-keys",
    "title": "Lost keys and recovery boundaries",
    "category": "Your two identities",
    "categoryId": "identities",
    "summary": "Understand what can be recovered, what cannot, and how to report a suspected compromise.",
    "body": [
      "AgoraNet cannot read or resend a Humanity Credential or identity access key because it stores only their hashes. An Alias deliberately has no True-Self-routed recovery path; creating one would become a correlation path.",
      "If you still have a signed-in browser, do not sign out until you understand the consequences. If you suspect compromise, stop using the affected key and open a critical support case. Support can explain and preserve evidence, but cannot promise to reverse an irreversible action."
    ],
    "keywords": [
      "lost key",
      "lost credential",
      "seed phrase",
      "recover account",
      "compromised",
      "stolen wallet"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "critical",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "owners-guide"
    ],
    "documentType": "recovery-boundary",
    "escalateWhen": "A key may be compromised, funds may be at risk, or you are unsure whether an existing signed-in session can be preserved."
  },
  {
    "id": "help.identities.switching-identities",
    "slug": "switching-identities",
    "title": "Switching identities; the profile menu",
    "category": "Your two identities",
    "categoryId": "identities",
    "summary": "Sign each identity in once per browser; after that, switching is one click.",
    "body": [
      "Your True Self and Alias each use their own access key at /login. Sign in to each one once per browser; after that, both identities appear in the profile bubble at the bottom-right.",
      "To switch identities, open the profile bubble and select True Self or Alias. Switching ends the current identity's pillar sessions, so it is always clear which identity is acting."
    ],
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "owners-guide"
    ],
    "documentType": "procedure",
    "links": [
      {
        "href": "/login",
        "label": "Sign in an identity"
      }
    ]
  },
  {
    "id": "help.identities.two-identities",
    "slug": "two-identities",
    "title": "True Self and Alias; one human, two identities",
    "category": "Your two identities",
    "categoryId": "identities",
    "summary": "Every human gets exactly one of each; the platform never stores a link between them.",
    "body": [
      "Your True Self is the identity you sign publicly. Every user can also have one Alias for sensitive conversations, personal experiences, or arguments they do not want tied to their public name.",
      "Every human gets exactly one Alias, enforced by a blind check: the platform can tell someone is trying twice without learning who. No record anywhere connects your two identities; not in the database, not in the ledger, not in search. That unlinkability is why the Alias ceremony asks for your Humanity Credential instead of your signed-in account.",
      "A new Alias is available immediately but starts invisible to the community. You decide when to make it public using the visibility control. The room's color always tells you whether you are using your True Self or Alias."
    ],
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/alias",
        "label": "The Alias ceremony"
      }
    ]
  },
  {
    "id": "help.platform-features.circles",
    "slug": "circles",
    "title": "Circles and membership",
    "category": "Using AgoraNet",
    "categoryId": "platform-features",
    "summary": "Public storefronts help discovery; members' rooms stay inside the Circle.",
    "body": [
      "A Circle is a place for coordinated work. Its public page can appear in search, while its members' room never enters the public index.",
      "Joining, leaving, offers, actions, and attestations are performed by the active identity. Check the identity theme before acting."
    ],
    "keywords": [
      "circle",
      "join circle",
      "members room",
      "place",
      "initiative"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/circles",
        "label": "Browse Circles"
      }
    ]
  },
  {
    "id": "help.platform-features.discussions",
    "slug": "discussions",
    "title": "Discussions, replies, and sources",
    "category": "Using AgoraNet",
    "categoryId": "platform-features",
    "summary": "Join a conversation, understand permanence, and attach sources honestly.",
    "body": [
      "Public Discussions and replies can be read by everyone. Acting requires an active verified identity and passes through the same gate as every other write.",
      "Before posting, read the permanence badge. Source objects preserve the cited URL and let search find every public conversation using that source."
    ],
    "keywords": [
      "post",
      "reply",
      "discussion",
      "citation",
      "source",
      "permanent"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/discussions",
        "label": "Browse Discussions"
      }
    ]
  },
  {
    "id": "help.platform-features.fellow-souls-dms",
    "slug": "fellow-souls-dms",
    "title": "Fellow souls and direct messages",
    "category": "Using AgoraNet",
    "categoryId": "platform-features",
    "summary": "Connections and messages are private to the active identity and absent from public search.",
    "body": [
      "Fellow-soul relationships and direct-message threads belong to one identity. They never bridge to the other identity and never appear in public search.",
      "A stranger message begins as a request and carries the published opening cost. A recipient can report the relevant excerpt as evidence; the rest of the thread does not become public."
    ],
    "keywords": [
      "friend",
      "fellow soul",
      "dm",
      "message",
      "connection request",
      "inbox"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/souls",
        "label": "Fellow Souls & Messages"
      }
    ]
  },
  {
    "id": "help.platform-features.polls-voting",
    "slug": "polls-voting",
    "title": "Polls and voting",
    "category": "Using AgoraNet",
    "categoryId": "platform-features",
    "summary": "How ordinary and governance polls work, including fees and sealed closes.",
    "body": [
      "Polls use one-person rules enforced at the gate. A vote fee is a participation cost, never vote weight; paying more never creates more influence.",
      "Some polls conceal the live tally or use a candle close to reduce bandwagoning and last-second manipulation. The poll page states the applicable rules before a ballot is cast."
    ],
    "keywords": [
      "poll",
      "vote",
      "ballot",
      "sealed tally",
      "candle close",
      "vote fee"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/governance",
        "label": "Polls & Governance"
      }
    ]
  },
  {
    "id": "help.platform-features.search",
    "slug": "search",
    "title": "Search; nine kinds of thing, one box",
    "category": "Using AgoraNet",
    "categoryId": "platform-features",
    "summary": "Content, souls, places, canon, records, polls, sources, help; same results for everyone.",
    "body": [
      "The one box at /search finds nine kinds of thing: content (Discussions, replies, Circle pages, Chamber storefronts), souls by @handle or display name, your own fellow souls, places, the pillars and canon, civic records, polls, cited sources, and help.",
      "Ranking is published and identical for everyone: match quality plus substance signals like participants and citations. Never views, never dwell time, never personalization; same query, same results, for every soul. Your search history is stored per identity, visible to you alone, deletable one-by-one or all at once, and never used to rank anything.",
      "Never in the index: direct messages, workshop and members'-room interiors, moderator identities, and anything that could bridge a soul's two identities."
    ],
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "feed-search-spec",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/search",
        "label": "Search"
      },
      {
        "href": "/search/about",
        "label": "How results are ranked"
      },
      {
        "href": "/search/history",
        "label": "Your search history"
      }
    ]
  },
  {
    "id": "help.platform-features.your-feed",
    "slug": "your-feed",
    "title": "Your feed; chosen sources only",
    "category": "Using AgoraNet",
    "categoryId": "platform-features",
    "summary": "Assembled only from sources you picked; the machine never watches you to guess.",
    "body": [
      "The feed on your dashboard carries only what you chose to follow; pillars, Discussions, Circles. The machine never watches your behavior to guess what you want; if you didn't choose a source, it cannot appear.",
      "It is private to each identity: your True Self and your Alias each keep their own list, because a shared list would be a bridge between them. Signed-out readers see the open lens instead; one stream ranked by a published formula, the same for everyone."
    ],
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "feed-search-spec",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/feed/sources",
        "label": "Choose what feeds you"
      }
    ]
  },
  {
    "id": "help.privacy-safety.moderation-appeals",
    "slug": "moderation-appeals",
    "title": "Moderation review and appeals",
    "category": "Privacy, safety & rules",
    "categoryId": "privacy-safety",
    "summary": "Support can explain the process, but only the authorized moderation path can change an outcome.",
    "body": [
      "Moderation outcomes are made through the platform's rule-bound adjudication process. The helpdesk can explain a rule or help with a broken appeal form; it cannot change a ruling.",
      "Use the appeal control attached to the case when available. A support case may preserve a technical problem, but it does not replace the appeal itself."
    ],
    "keywords": [
      "moderation",
      "appeal",
      "strike",
      "ruling",
      "case"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "high",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "platform-constitution",
      "moderation-spec",
      "owners-guide"
    ],
    "documentType": "procedure",
    "escalateWhen": "The appeal control is unavailable or technically fails before its deadline.",
    "links": [
      {
        "href": "/rules",
        "label": "The rulebook"
      }
    ]
  },
  {
    "id": "help.privacy-safety.permanence",
    "slug": "permanence",
    "title": "Permanent record vs author-deletable",
    "category": "Privacy, safety & rules",
    "categoryId": "privacy-safety",
    "summary": "Some rooms are written in ink; the room always tells you before you speak.",
    "body": [
      "Some spaces on AgoraNet are permanent: what you post there enters the public record by content hash, anchored on-chain, and nobody; including the platform; holds a pen that can rewrite it. Other spaces are author-deletable: you can remove your own words later.",
      "The permanence badge is a cross-theme constant; the same amber in every room, on every identity; because some truths outrank identity. You will always see it before you post, never after.",
      "Display names can change; the permanent record keeps the name a thing was written under. That, too, is the point: the record nobody can rewrite includes us."
    ],
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "platform-constitution",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/record",
        "label": "The Public Record"
      }
    ]
  },
  {
    "id": "help.privacy-safety.privacy-profile-boundaries",
    "slug": "privacy-profile-boundaries",
    "title": "Privacy and profile boundaries",
    "category": "Privacy, safety & rules",
    "categoryId": "privacy-safety",
    "summary": "Support remains scoped to the active identity and never uses help-seeking as a reputation signal.",
    "body": [
      "A helpdesk conversation or case is scoped to the identity active when it is created. Support does not search for, infer, or reveal another persona.",
      "Help-seeking is never an input to Light Score, feed ranking, search ranking, moderation selection, or civic standing. Diagnostic context is limited to the current feature, stage, non-secret error code, and client version."
    ],
    "keywords": [
      "privacy",
      "alias link",
      "cross persona",
      "support history",
      "search history"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "high",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "platform-constitution",
      "owners-guide"
    ],
    "documentType": "concept"
  },
  {
    "id": "help.privacy-safety.report-content",
    "slug": "report-content",
    "title": "Report content or behavior",
    "category": "Privacy, safety & rules",
    "categoryId": "privacy-safety",
    "summary": "Use the in-product report path for moderation; use Support for technical or safety help.",
    "body": [
      "Use the report control beside the content or message whenever possible. It preserves the exact item and sends only the evidence needed for review.",
      "For immediate safety, privacy exposure, or a report control that does not work, open a high-priority support case. Do not copy sensitive material into a public Discussion."
    ],
    "keywords": [
      "report",
      "harassment",
      "abuse",
      "unsafe",
      "flag",
      "moderation"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "high",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "platform-constitution",
      "moderation-spec",
      "owners-guide"
    ],
    "documentType": "procedure",
    "escalateWhen": "There is a safety threat, privacy exposure, account compromise, or the normal report path is unavailable.",
    "links": [
      {
        "href": "/rules",
        "label": "Read the moderation rules"
      }
    ]
  },
  {
    "id": "help.troubleshooting.browser-technical-help",
    "slug": "browser-technical-help",
    "title": "Browser and connection troubleshooting",
    "category": "Troubleshooting",
    "categoryId": "troubleshooting",
    "summary": "Safe first checks for loading, session, and feature errors.",
    "body": [
      "Refresh once, confirm the browser is online, and retry the exact action once. If the issue involves a wallet, unlock the wallet and check its selected network.",
      "Do not clear cookies or sign out if you may have lost an access key; an existing signed-in session may be valuable. Open support first and describe the screen, action, and non-secret error code."
    ],
    "keywords": [
      "page not loading",
      "technical help",
      "browser error",
      "session",
      "stuck",
      "network error"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "troubleshooting",
    "escalateWhen": "The same action fails twice, the page cannot load, or clearing local state could strand an identity."
  },
  {
    "id": "help.troubleshooting.contact-support",
    "slug": "contact-support",
    "title": "Open a support request",
    "category": "Troubleshooting",
    "categoryId": "troubleshooting",
    "summary": "What to include, what never to send, and what happens after submission.",
    "body": [
      "Describe what you expected, what happened, the current screen or onboarding stage, and any non-secret error code. A screenshot is useful only after checking that it contains no credential, access key, seed phrase, private message, or unrelated personal information.",
      "You will receive a case reference. The case is scoped to the active identity; a guest provides a reply email explicitly. Support can investigate and explain, but consequential changes remain with the authorized identity, moderation, security, or treasury process."
    ],
    "keywords": [
      "contact support",
      "support ticket",
      "help request",
      "human",
      "case"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "procedure",
    "escalateWhen": "Self-service did not resolve the issue or any high-risk condition applies."
  },
  {
    "id": "help.troubleshooting.known-issues",
    "slug": "known-issues",
    "title": "Known issues and service status",
    "category": "Troubleshooting",
    "categoryId": "troubleshooting",
    "summary": "Check whether a platform or test-rail incident already explains the problem.",
    "body": [
      "Known issues are published here when an active incident affects more than one soul. Each notice states the affected feature, first observed time, current workaround, and resolution status.",
      "No active incident is listed in this build. If you are seeing a repeatable failure, ask the helpdesk or open a support case so it can be compared with other reports."
    ],
    "keywords": [
      "known issue",
      "outage",
      "status",
      "down",
      "service unavailable"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "known-issue"
  },
  {
    "id": "help.troubleshooting.transaction-pending",
    "slug": "transaction-pending",
    "title": "A transaction is pending or failed",
    "category": "Troubleshooting",
    "categoryId": "troubleshooting",
    "summary": "Check network and chain status, then preserve the transaction hash for support.",
    "body": [
      "Confirm that the wallet and platform are using the same test network. A submitted transaction may remain pending while the network confirms it; a wallet rejection means it was not submitted.",
      "If a transaction hash exists, keep it. If no hash exists, record the non-secret error text and the action you attempted. Never retry a value-moving action repeatedly without first checking whether the earlier transaction landed."
    ],
    "keywords": [
      "transaction pending",
      "transaction failed",
      "tx hash",
      "chain",
      "balance missing"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "high",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "economy-specs",
      "owners-guide"
    ],
    "documentType": "troubleshooting",
    "escalateWhen": "A confirmed transaction is not reflected, the balance is unexpected, or repeated attempts could duplicate the action."
  },
  {
    "id": "help.troubleshooting.verification-troubleshooting",
    "slug": "verification-troubleshooting",
    "title": "Verification is pending, rejected, or interrupted",
    "category": "Troubleshooting",
    "categoryId": "troubleshooting",
    "summary": "Resume safely, understand the current test-rail limits, and know when a human must review the issue.",
    "body": [
      "Start from the gate again in the same browser. A page refresh or closed tab does not create a second identity; incomplete ceremonies simply return to the last safe boundary.",
      "If the gate reports an error, copy the non-secret error code and the stage where it happened. Never send your Humanity Credential, access key, wallet seed phrase, or private key to support.",
      "A verification decision that requires review cannot be changed by the helpdesk. Open a support case so a human can inspect the safe diagnostic record."
    ],
    "keywords": [
      "verification failed",
      "verification pending",
      "stuck onboarding",
      "issuer",
      "proof of humanity"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate"
    ],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "high",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ],
    "documentType": "troubleshooting",
    "escalateWhen": "The same verification step fails twice, the issuer reports a rejection, or you suspect your credential was exposed.",
    "links": [
      {
        "href": "/verify",
        "label": "Return to the gate"
      }
    ]
  },
  {
    "id": "help.troubleshooting.wallet-connection",
    "slug": "wallet-connection",
    "title": "Wallet connection troubleshooting",
    "category": "Troubleshooting",
    "categoryId": "troubleshooting",
    "summary": "Check the selected network, wallet approval, and connector before opening a case.",
    "body": [
      "AgoraNet's current chain features use Cardano test rails. Confirm that Lace is installed, unlocked, and set to the network shown by the platform. Then reload the page and approve the connection in the wallet window.",
      "A wallet address or transaction hash may be shared in a support case when needed. A seed phrase, spending password, signing key, or private key must never be shared."
    ],
    "keywords": [
      "wallet not connecting",
      "Lace",
      "CIP-30",
      "preprod",
      "wrong network",
      "wallet error"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.0.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "troubleshooting",
    "escalateWhen": "The wallet remains unavailable after reload, the network is correct, and the wallet itself shows no pending approval."
  }
] as const;
export const GENERATED_HELP_RETRIEVAL_DOCUMENTS = [
  {
    "id": "help.economy.donations-treasury",
    "slug": "donations-treasury",
    "title": "Donations and the treasury",
    "summary": "Follow public flows and understand the difference between internal balances and test-rail transactions.",
    "text": "The transparency surface shows published rails and treasury records. Current internal balances and test-rail assets are labeled honestly; one must not be mistaken for the other.\n\nFor a transaction problem, preserve the public transaction hash and the exact time. Never send a seed phrase or signing key. Missing-value reports require human review.",
    "audience": "public",
    "categoryId": "economy",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "donation",
      "treasury",
      "balance",
      "funds",
      "transaction",
      "dPOLL"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "economy-specs",
      "owners-guide"
    ],
    "escalateWhen": "A confirmed transaction is absent from the platform, a balance changed unexpectedly, or compromise is suspected."
  },
  {
    "id": "help.economy.money",
    "slug": "money",
    "title": "PollCoin, Gratium, and fees",
    "summary": "Two currencies, published rails, and an economy that cannot sell attention.",
    "text": "The platform runs on two internal currencies: PollCoin (PC) and Gratium (G). New identities hatch with a grant of each, so nobody is born traceable by poverty and first actions are free.\n\nFees and deposits are the platform's real throttle; they make floods expensive while a deliberating human never notices them. Every number is a rail: published, bounded, and poll-adjustable by the community. The full table lives on the transparency page; searching the help lane also surfaces individual rails.\n\nThe economy cannot sell attention because it never captures attention: no views, no dwell time, no engagement metrics exist anywhere in the system.",
    "audience": "public",
    "categoryId": "economy",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "economy-specs",
      "owners-guide"
    ]
  },
  {
    "id": "help.getting-started.onboarding-interrupted",
    "slug": "onboarding-interrupted",
    "title": "Onboarding was interrupted",
    "summary": "Return to the journey without sharing or recreating secrets unnecessarily.",
    "text": "Return to the gate in the same browser. AgoraNet will carry forward any completed server-side stage and will never ask support to reconstruct a secret that was shown once.\n\nIf you already created an identity and saved its access key, use Sign in instead of beginning again. If a one-time secret was shown but not saved, read the recovery-boundary article before taking another action.",
    "audience": "public",
    "categoryId": "getting-started",
    "documentType": "troubleshooting",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "onboarding stuck",
      "continue onboarding",
      "closed browser",
      "resume",
      "start over"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate",
      "credential",
      "identity",
      "alias",
      "values"
    ],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.getting-started.values-seed",
    "slug": "values-seed",
    "title": "The values seed and your first action",
    "summary": "Seven small answers orient your experience; they are not a universal score.",
    "text": "The values seed asks one question from each pillar. It gives your new identity a starting orientation and helps relevant parts of the commons become visible.\n\nIt is not a test, personality label, or cross-profile score. Each identity has its own answers. Completing onboarding carries you back to the action that brought you to the gate.",
    "audience": "public",
    "categoryId": "getting-started",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "values seed",
      "seven questions",
      "first action",
      "orientation"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.getting-started.verify-once",
    "slug": "verify-once",
    "title": "Verify once, act forever",
    "summary": "Reading is free for everyone; acting requires proving you're one real human, once.",
    "text": "Everything on AgoraNet can be read without an account; search, Discussions, the Public Record, poll results. Reading is free, forever, and nobody watches you do it.\n\nActing; posting, voting, joining Circles; requires passing the gate once: the ceremony at /verify proves you are one real human and hands you a Humanity Credential. That credential is the root of everything else; the platform stores only a hash of it, so it is shown to you exactly once.\n\nFrom the credential you register your True Self: your signed public identity, with its own @handle and access key. The access key is how this browser signs that identity in; also shown once, also unrecoverable if lost. Save both somewhere real.",
    "audience": "public",
    "categoryId": "getting-started",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [
      "gate"
    ],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.getting-started.what-to-save",
    "slug": "what-to-save",
    "title": "Your two codes; what to save, and what loss means",
    "summary": "The Humanity Credential and each identity's access key are shown once and never recoverable.",
    "text": "The platform never stores your secrets in a readable form; only hashes. That is a feature: nobody can take from the platform what the platform does not hold. The cost is honest and permanent: a lost secret is gone.\n\nYou hold two kinds of secret. Your Humanity Credential is the passport; it proves one-real-human at ceremonies like hatching an Alias. Each identity's access key is a house key; it signs that identity into a browser.\n\nLosing an access key means that identity can never be signed in anywhere new. Losing the credential means no new ceremonies; though identities already signed in keep working. Write them down somewhere real the moment they are shown.",
    "audience": "public",
    "categoryId": "getting-started",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.identities.lost-keys",
    "slug": "lost-keys",
    "title": "Lost keys and recovery boundaries",
    "summary": "Understand what can be recovered, what cannot, and how to report a suspected compromise.",
    "text": "AgoraNet cannot read or resend a Humanity Credential or identity access key because it stores only their hashes. An Alias deliberately has no True-Self-routed recovery path; creating one would become a correlation path.\n\nIf you still have a signed-in browser, do not sign out until you understand the consequences. If you suspect compromise, stop using the affected key and open a critical support case. Support can explain and preserve evidence, but cannot promise to reverse an irreversible action.",
    "audience": "public",
    "categoryId": "identities",
    "documentType": "recovery-boundary",
    "risk": "critical",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "lost key",
      "lost credential",
      "seed phrase",
      "recover account",
      "compromised",
      "stolen wallet"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "owners-guide"
    ],
    "escalateWhen": "A key may be compromised, funds may be at risk, or you are unsure whether an existing signed-in session can be preserved."
  },
  {
    "id": "help.identities.switching-identities",
    "slug": "switching-identities",
    "title": "Switching identities; the profile menu",
    "summary": "Sign each identity in once per browser; after that, switching is one click.",
    "text": "Your True Self and Alias each use their own access key at /login. Sign in to each one once per browser; after that, both identities appear in the profile bubble at the bottom-right.\n\nTo switch identities, open the profile bubble and select True Self or Alias. Switching ends the current identity's pillar sessions, so it is always clear which identity is acting.",
    "audience": "public",
    "categoryId": "identities",
    "documentType": "procedure",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.identities.two-identities",
    "slug": "two-identities",
    "title": "True Self and Alias; one human, two identities",
    "summary": "Every human gets exactly one of each; the platform never stores a link between them.",
    "text": "Your True Self is the identity you sign publicly. Every user can also have one Alias for sensitive conversations, personal experiences, or arguments they do not want tied to their public name.\n\nEvery human gets exactly one Alias, enforced by a blind check: the platform can tell someone is trying twice without learning who. No record anywhere connects your two identities; not in the database, not in the ledger, not in search. That unlinkability is why the Alias ceremony asks for your Humanity Credential instead of your signed-in account.\n\nA new Alias is available immediately but starts invisible to the community. You decide when to make it public using the visibility control. The room's color always tells you whether you are using your True Self or Alias.",
    "audience": "public",
    "categoryId": "identities",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.platform-features.circles",
    "slug": "circles",
    "title": "Circles and membership",
    "summary": "Public storefronts help discovery; members' rooms stay inside the Circle.",
    "text": "A Circle is a place for coordinated work. Its public page can appear in search, while its members' room never enters the public index.\n\nJoining, leaving, offers, actions, and attestations are performed by the active identity. Check the identity theme before acting.",
    "audience": "public",
    "categoryId": "platform-features",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "circle",
      "join circle",
      "members room",
      "place",
      "initiative"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ]
  },
  {
    "id": "help.platform-features.discussions",
    "slug": "discussions",
    "title": "Discussions, replies, and sources",
    "summary": "Join a conversation, understand permanence, and attach sources honestly.",
    "text": "Public Discussions and replies can be read by everyone. Acting requires an active verified identity and passes through the same gate as every other write.\n\nBefore posting, read the permanence badge. Source objects preserve the cited URL and let search find every public conversation using that source.",
    "audience": "public",
    "categoryId": "platform-features",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "post",
      "reply",
      "discussion",
      "citation",
      "source",
      "permanent"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ]
  },
  {
    "id": "help.platform-features.fellow-souls-dms",
    "slug": "fellow-souls-dms",
    "title": "Fellow souls and direct messages",
    "summary": "Connections and messages are private to the active identity and absent from public search.",
    "text": "Fellow-soul relationships and direct-message threads belong to one identity. They never bridge to the other identity and never appear in public search.\n\nA stranger message begins as a request and carries the published opening cost. A recipient can report the relevant excerpt as evidence; the rest of the thread does not become public.",
    "audience": "public",
    "categoryId": "platform-features",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "friend",
      "fellow soul",
      "dm",
      "message",
      "connection request",
      "inbox"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ]
  },
  {
    "id": "help.platform-features.polls-voting",
    "slug": "polls-voting",
    "title": "Polls and voting",
    "summary": "How ordinary and governance polls work, including fees and sealed closes.",
    "text": "Polls use one-person rules enforced at the gate. A vote fee is a participation cost, never vote weight; paying more never creates more influence.\n\nSome polls conceal the live tally or use a candle close to reduce bandwagoning and last-second manipulation. The poll page states the applicable rules before a ballot is cast.",
    "audience": "public",
    "categoryId": "platform-features",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "poll",
      "vote",
      "ballot",
      "sealed tally",
      "candle close",
      "vote fee"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ]
  },
  {
    "id": "help.platform-features.search",
    "slug": "search",
    "title": "Search; nine kinds of thing, one box",
    "summary": "Content, souls, places, canon, records, polls, sources, help; same results for everyone.",
    "text": "The one box at /search finds nine kinds of thing: content (Discussions, replies, Circle pages, Chamber storefronts), souls by @handle or display name, your own fellow souls, places, the pillars and canon, civic records, polls, cited sources, and help.\n\nRanking is published and identical for everyone: match quality plus substance signals like participants and citations. Never views, never dwell time, never personalization; same query, same results, for every soul. Your search history is stored per identity, visible to you alone, deletable one-by-one or all at once, and never used to rank anything.\n\nNever in the index: direct messages, workshop and members'-room interiors, moderator identities, and anything that could bridge a soul's two identities.",
    "audience": "public",
    "categoryId": "platform-features",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "feed-search-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.platform-features.your-feed",
    "slug": "your-feed",
    "title": "Your feed; chosen sources only",
    "summary": "Assembled only from sources you picked; the machine never watches you to guess.",
    "text": "The feed on your dashboard carries only what you chose to follow; pillars, Discussions, Circles. The machine never watches your behavior to guess what you want; if you didn't choose a source, it cannot appear.\n\nIt is private to each identity: your True Self and your Alias each keep their own list, because a shared list would be a bridge between them. Signed-out readers see the open lens instead; one stream ranked by a published formula, the same for everyone.",
    "audience": "public",
    "categoryId": "platform-features",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "feed-search-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.privacy-safety.moderation-appeals",
    "slug": "moderation-appeals",
    "title": "Moderation review and appeals",
    "summary": "Support can explain the process, but only the authorized moderation path can change an outcome.",
    "text": "Moderation outcomes are made through the platform's rule-bound adjudication process. The helpdesk can explain a rule or help with a broken appeal form; it cannot change a ruling.\n\nUse the appeal control attached to the case when available. A support case may preserve a technical problem, but it does not replace the appeal itself.",
    "audience": "public",
    "categoryId": "privacy-safety",
    "documentType": "procedure",
    "risk": "high",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "moderation",
      "appeal",
      "strike",
      "ruling",
      "case"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "platform-constitution",
      "moderation-spec",
      "owners-guide"
    ],
    "escalateWhen": "The appeal control is unavailable or technically fails before its deadline."
  },
  {
    "id": "help.privacy-safety.permanence",
    "slug": "permanence",
    "title": "Permanent record vs author-deletable",
    "summary": "Some rooms are written in ink; the room always tells you before you speak.",
    "text": "Some spaces on AgoraNet are permanent: what you post there enters the public record by content hash, anchored on-chain, and nobody; including the platform; holds a pen that can rewrite it. Other spaces are author-deletable: you can remove your own words later.\n\nThe permanence badge is a cross-theme constant; the same amber in every room, on every identity; because some truths outrank identity. You will always see it before you post, never after.\n\nDisplay names can change; the permanent record keeps the name a thing was written under. That, too, is the point: the record nobody can rewrite includes us.",
    "audience": "public",
    "categoryId": "privacy-safety",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "platform-constitution",
      "owners-guide"
    ]
  },
  {
    "id": "help.privacy-safety.privacy-profile-boundaries",
    "slug": "privacy-profile-boundaries",
    "title": "Privacy and profile boundaries",
    "summary": "Support remains scoped to the active identity and never uses help-seeking as a reputation signal.",
    "text": "A helpdesk conversation or case is scoped to the identity active when it is created. Support does not search for, infer, or reveal another persona.\n\nHelp-seeking is never an input to Light Score, feed ranking, search ranking, moderation selection, or civic standing. Diagnostic context is limited to the current feature, stage, non-secret error code, and client version.",
    "audience": "public",
    "categoryId": "privacy-safety",
    "documentType": "concept",
    "risk": "high",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "privacy",
      "alias link",
      "cross persona",
      "support history",
      "search history"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "platform-constitution",
      "owners-guide"
    ]
  },
  {
    "id": "help.privacy-safety.report-content",
    "slug": "report-content",
    "title": "Report content or behavior",
    "summary": "Use the in-product report path for moderation; use Support for technical or safety help.",
    "text": "Use the report control beside the content or message whenever possible. It preserves the exact item and sends only the evidence needed for review.\n\nFor immediate safety, privacy exposure, or a report control that does not work, open a high-priority support case. Do not copy sensitive material into a public Discussion.",
    "audience": "public",
    "categoryId": "privacy-safety",
    "documentType": "procedure",
    "risk": "high",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "report",
      "harassment",
      "abuse",
      "unsafe",
      "flag",
      "moderation"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "platform-constitution",
      "moderation-spec",
      "owners-guide"
    ],
    "escalateWhen": "There is a safety threat, privacy exposure, account compromise, or the normal report path is unavailable."
  },
  {
    "id": "help.troubleshooting.browser-technical-help",
    "slug": "browser-technical-help",
    "title": "Browser and connection troubleshooting",
    "summary": "Safe first checks for loading, session, and feature errors.",
    "text": "Refresh once, confirm the browser is online, and retry the exact action once. If the issue involves a wallet, unlock the wallet and check its selected network.\n\nDo not clear cookies or sign out if you may have lost an access key; an existing signed-in session may be valuable. Open support first and describe the screen, action, and non-secret error code.",
    "audience": "public",
    "categoryId": "troubleshooting",
    "documentType": "troubleshooting",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "page not loading",
      "technical help",
      "browser error",
      "session",
      "stuck",
      "network error"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "escalateWhen": "The same action fails twice, the page cannot load, or clearing local state could strand an identity."
  },
  {
    "id": "help.troubleshooting.contact-support",
    "slug": "contact-support",
    "title": "Open a support request",
    "summary": "What to include, what never to send, and what happens after submission.",
    "text": "Describe what you expected, what happened, the current screen or onboarding stage, and any non-secret error code. A screenshot is useful only after checking that it contains no credential, access key, seed phrase, private message, or unrelated personal information.\n\nYou will receive a case reference. The case is scoped to the active identity; a guest provides a reply email explicitly. Support can investigate and explain, but consequential changes remain with the authorized identity, moderation, security, or treasury process.",
    "audience": "public",
    "categoryId": "troubleshooting",
    "documentType": "procedure",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "contact support",
      "support ticket",
      "help request",
      "human",
      "case"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "escalateWhen": "Self-service did not resolve the issue or any high-risk condition applies."
  },
  {
    "id": "help.troubleshooting.known-issues",
    "slug": "known-issues",
    "title": "Known issues and service status",
    "summary": "Check whether a platform or test-rail incident already explains the problem.",
    "text": "Known issues are published here when an active incident affects more than one soul. Each notice states the affected feature, first observed time, current workaround, and resolution status.\n\nNo active incident is listed in this build. If you are seeing a repeatable failure, ask the helpdesk or open a support case so it can be compared with other reports.",
    "audience": "public",
    "categoryId": "troubleshooting",
    "documentType": "known-issue",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "known issue",
      "outage",
      "status",
      "down",
      "service unavailable"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ]
  },
  {
    "id": "help.troubleshooting.transaction-pending",
    "slug": "transaction-pending",
    "title": "A transaction is pending or failed",
    "summary": "Check network and chain status, then preserve the transaction hash for support.",
    "text": "Confirm that the wallet and platform are using the same test network. A submitted transaction may remain pending while the network confirms it; a wallet rejection means it was not submitted.\n\nIf a transaction hash exists, keep it. If no hash exists, record the non-secret error text and the action you attempted. Never retry a value-moving action repeatedly without first checking whether the earlier transaction landed.",
    "audience": "public",
    "categoryId": "troubleshooting",
    "documentType": "troubleshooting",
    "risk": "high",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "transaction pending",
      "transaction failed",
      "tx hash",
      "chain",
      "balance missing"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "economy-specs",
      "owners-guide"
    ],
    "escalateWhen": "A confirmed transaction is not reflected, the balance is unexpected, or repeated attempts could duplicate the action."
  },
  {
    "id": "help.troubleshooting.verification-troubleshooting",
    "slug": "verification-troubleshooting",
    "title": "Verification is pending, rejected, or interrupted",
    "summary": "Resume safely, understand the current test-rail limits, and know when a human must review the issue.",
    "text": "Start from the gate again in the same browser. A page refresh or closed tab does not create a second identity; incomplete ceremonies simply return to the last safe boundary.\n\nIf the gate reports an error, copy the non-secret error code and the stage where it happened. Never send your Humanity Credential, access key, wallet seed phrase, or private key to support.\n\nA verification decision that requires review cannot be changed by the helpdesk. Open a support case so a human can inspect the safe diagnostic record.",
    "audience": "public",
    "categoryId": "troubleshooting",
    "documentType": "troubleshooting",
    "risk": "high",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "verification failed",
      "verification pending",
      "stuck onboarding",
      "issuer",
      "proof of humanity"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate"
    ],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ],
    "escalateWhen": "The same verification step fails twice, the issuer reports a rejection, or you suspect your credential was exposed."
  },
  {
    "id": "help.troubleshooting.wallet-connection",
    "slug": "wallet-connection",
    "title": "Wallet connection troubleshooting",
    "summary": "Check the selected network, wallet approval, and connector before opening a case.",
    "text": "AgoraNet's current chain features use Cardano test rails. Confirm that Lace is installed, unlocked, and set to the network shown by the platform. Then reload the page and approve the connection in the wallet window.\n\nA wallet address or transaction hash may be shared in a support case when needed. A seed phrase, spending password, signing key, or private key must never be shared.",
    "audience": "public",
    "categoryId": "troubleshooting",
    "documentType": "troubleshooting",
    "risk": "normal",
    "version": "1.0.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "wallet not connecting",
      "Lace",
      "CIP-30",
      "preprod",
      "wrong network",
      "wallet error"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "escalateWhen": "The wallet remains unavailable after reload, the network is correct, and the wallet itself shows no pending approval."
  },
  {
    "id": "internal.capability.current",
    "title": "Current helpdesk capability matrix",
    "summary": "Distinguishes implemented support functions from planned or unavailable functions.",
    "text": "Implemented: public Help Center, twenty-five approved public articles, help search, contextual onboarding links, deterministic grounded guidance, grounded model-generated answers from the protected Gemma testnet runtime, secret rejection, support-case creation, rate limits, an internal command-line case queue, and a restricted browser-based operator console.\n\nModel generation uses only application-selected approved evidence and must fall back safely to deterministic guidance when the protected runtime is unavailable.\n\nNot implemented: account or secret recovery, automatic transaction reversal, verification-decision changes, moderation-decision changes, automatic email delivery, a staffed response-time promise, and an in-product support inbox for end users.\n\nNever claim that a planned or simulated capability is available in the deployed product.",
    "audience": "operator",
    "categoryId": "platform-features",
    "documentType": "capability-matrix",
    "risk": "high",
    "version": "1.1.0",
    "effectiveAt": "2026-08-23",
    "reviewBy": "2026-11-23",
    "keywords": [
      "capability",
      "implemented",
      "unavailable",
      "support operations"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owners-guide"
    ],
    "escalateWhen": "A request depends on a capability not listed as implemented."
  },
  {
    "id": "internal.errors.core",
    "title": "Core support error-handling catalog",
    "summary": "Defines how unregistered error codes and repeatable failures are handled safely.",
    "text": "Only codes explicitly registered in this corpus may be interpreted. An unfamiliar code is recorded as safe diagnostic context; the helpdesk must not infer its meaning from its name.\n\nFor an unregistered code, capture only the route, onboarding stage, client version, timestamp, and code. Do not request screenshots or copied text that may contain credentials or private information unless an approved procedure defines the evidence boundary.\n\nIf the same safe step fails twice, offer a human support request and preserve the non-secret code. Consequential categories use the deterministic severity floor.",
    "audience": "operator",
    "categoryId": "troubleshooting",
    "documentType": "error-catalog",
    "risk": "high",
    "version": "1.0.0",
    "effectiveAt": "2026-08-23",
    "reviewBy": "2026-11-23",
    "keywords": [
      "error code",
      "repeatable failure",
      "diagnostics"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate",
      "credential",
      "identity",
      "alias",
      "values"
    ],
    "sourceRefs": [
      "help-support-spec",
      "owners-guide"
    ],
    "escalateWhen": "An error repeats after the approved safe step, blocks onboarding, or could involve identity, funds, privacy, or security."
  },
  {
    "id": "internal.escalation.core",
    "title": "Core helpdesk escalation matrix",
    "summary": "Establishes severity floors and the boundary between self-service and human review.",
    "text": "Critical: active compromise, reported security vulnerability, exposed private data, or potentially missing funds. Stop self-service and route for urgent human review without promising a response time that operations has not ratified.\n\nHigh: repeated onboarding blockage, verification review, lost keys, privacy or harassment concerns, moderation appeals, and suspected compromise without an active-loss signal.\n\nNormal: repeatable feature malfunction, pending transaction, or technical failure that remains unresolved after approved safe steps.\n\nInformational: supported how-to and policy questions. The model may raise severity but never reduce the deterministic application classification.",
    "audience": "operator",
    "categoryId": "privacy-safety",
    "documentType": "escalation-matrix",
    "risk": "critical",
    "version": "1.0.0",
    "effectiveAt": "2026-08-23",
    "reviewBy": "2026-11-23",
    "keywords": [
      "escalation",
      "severity",
      "compromise",
      "missing funds",
      "verification",
      "moderation"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "dual-identity-spec",
      "moderation-spec"
    ],
    "escalateWhen": "Any mandatory category below is detected."
  },
  {
    "id": "internal.troubleshooting.onboarding",
    "title": "Onboarding troubleshooting tree",
    "summary": "Provides a bounded sequence for interrupted or repeatedly failing onboarding.",
    "text": "First identify the current stage from allowlisted context or ask one focused question. Do not ask the user to repeat a completed ceremony or recreate an identity until the approved article establishes that it is safe.\n\nIf the browser was closed, direct the user to resume from the gate in the same browser. If an identity was already created and its access key was saved, direct the user to sign in instead of beginning again.\n\nIf a one-time secret was shown but may not have been saved, stop and apply the recovery-boundary guidance. If verification was rejected or the same step fails twice, offer a human support request with the stage and non-secret error code.",
    "audience": "operator",
    "categoryId": "getting-started",
    "documentType": "troubleshooting-tree",
    "risk": "high",
    "version": "1.0.0",
    "effectiveAt": "2026-08-23",
    "reviewBy": "2026-11-23",
    "keywords": [
      "onboarding stuck",
      "verification failed",
      "resume",
      "gate"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate",
      "credential",
      "identity",
      "alias",
      "values"
    ],
    "sourceRefs": [
      "help-support-spec",
      "onboarding-spec",
      "dual-identity-spec"
    ],
    "escalateWhen": "The same stage fails twice, verification needs review, or a one-time secret may be lost or exposed."
  },
  {
    "id": "policy.support.boundaries",
    "title": "Approved helpdesk authority and privacy boundaries",
    "summary": "Defines the non-negotiable limits on helpdesk knowledge, identity handling, secrets, and actions.",
    "text": "The helpdesk explains approved AgoraNet behavior and safe procedures. It does not change identity, verification, funds, moderation, recovery, privacy, or on-chain state.\n\nSupport information remains scoped to the active profile. Convenience never justifies correlating True Self and Alias. Private messages, members-room interiors, hidden moderation signals, and another profile's history are unavailable unless a separately approved, consented, role-gated procedure explicitly permits the minimum necessary evidence.\n\nThe helpdesk never requests or retains credentials, access keys, passwords, wallet seed phrases, private keys, signing keys, or authentication secrets. It does not promise recovery or reversal where AgoraNet holds no such capability.",
    "audience": "operator",
    "categoryId": "privacy-safety",
    "documentType": "policy",
    "risk": "critical",
    "version": "1.0.0",
    "effectiveAt": "2026-08-23",
    "reviewBy": "2026-11-23",
    "keywords": [
      "authority",
      "privacy",
      "secrets",
      "dual identity",
      "recovery"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "platform-constitution",
      "dual-identity-spec",
      "moderation-spec"
    ],
    "escalateWhen": "A request would exceed helpdesk authority or weaken identity, privacy, moderation, recovery, or financial safeguards."
  }
] as const;
