// Generated by scripts/compile-help-corpus.ts. DO NOT EDIT.
export const HELP_CORPUS_VERSION = "1.2.0+28a6ff5f3537677e" as const;
export const GENERATED_HELP_CATEGORIES = [
  "Getting started",
  "Your two identities",
  "Using AgoraNet",
  "Money, fees & treasury",
  "Privacy, safety & rules",
  "Troubleshooting"
] as const;
export const GENERATED_HELP_ARTICLES = [
  {
    "id": "help.economy.donations-treasury",
    "slug": "donations-treasury",
    "title": "Donations and the treasury",
    "category": "Money, fees & treasury",
    "categoryId": "economy",
    "summary": "Check published treasury activity and distinguish AgoraNet balances from test-network wallet transactions.",
    "body": [
      "Open Transparency for published fees and system activity. Open Treasury for public treasury balances and transactions. AgoraNet labels an internal platform balance separately from a Cardano test-network wallet transaction so you can tell which system you are looking at.",
      "If a donation or treasury transaction looks missing, first check whether your wallet shows it as pending, failed, or confirmed. Save the transaction hash, which is the public reference shown by the wallet, and note the approximate time.",
      "Do not retry a value-moving action repeatedly, and never send Support a wallet seed phrase, spending password, private key, or signing key. A confirmed transaction that is missing from AgoraNet, an unexpected balance change, or suspected theft requires a human support request."
    ],
    "keywords": [
      "donation",
      "treasury",
      "balance",
      "funds",
      "transaction",
      "dPOLL"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "economy-specs",
      "owners-guide"
    ],
    "documentType": "concept",
    "escalateWhen": "A confirmed transaction is absent from the platform, a balance changed unexpectedly, or compromise is suspected.",
    "links": [
      {
        "href": "/transparency",
        "label": "Transparency"
      },
      {
        "href": "/treasury",
        "label": "Treasury"
      }
    ]
  },
  {
    "id": "help.economy.money",
    "slug": "money",
    "title": "PollCoin, Gratium, and platform fees",
    "category": "Money, fees & treasury",
    "categoryId": "economy",
    "summary": "Learn what AgoraNet's two internal balances do, why small fees exist, and where to check the current amounts.",
    "body": [
      "AgoraNet uses two internal balances. PollCoin, shown as PC, pays platform participation fees and deposits. Gratium, shown as G, records appreciation. A new profile receives a starting amount of each so it can take its first actions.",
      "Small fees and refundable deposits discourage automated spam and repeated disruptive actions. A fee is not vote weight, reputation, or permission to break a rule. Current amounts and limits are published on Transparency and may change through the platform's approved voting process.",
      "AgoraNet does not sell or rank attention. Views, time spent reading, and engagement tracking are not used to build a personal advertising profile or to decide what appears in search."
    ],
    "keywords": [
      "PollCoin",
      "Gratium",
      "PC",
      "fee",
      "balance",
      "cost"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "economy-specs",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/transparency",
        "label": "View current fees and balances"
      }
    ]
  },
  {
    "id": "help.getting-started.onboarding-interrupted",
    "slug": "onboarding-interrupted",
    "title": "Onboarding was interrupted",
    "category": "Getting started",
    "categoryId": "getting-started",
    "summary": "Reopen account setup in the same browser, or sign in if you already created a profile and saved its access key.",
    "body": [
      "Open the account setup page in the same browser you used before. AgoraNet will carry forward any completed setup step. You do not need to remember the page's internal name, and Support will never ask you to reconstruct or share a private code that was shown once.",
      "If you already created a profile and saved its access key, open Sign in instead of beginning again. If an access key appeared but you did not save it, do not create another profile or send any private code to Support. Read “Save your Humanity Credential and access key” before taking another action."
    ],
    "keywords": [
      "onboarding stuck",
      "continue onboarding",
      "closed browser",
      "resume",
      "start over"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate",
      "credential",
      "identity",
      "alias",
      "values"
    ],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ],
    "documentType": "troubleshooting",
    "links": [
      {
        "href": "/verify",
        "label": "Resume onboarding"
      },
      {
        "href": "/login",
        "label": "Sign in"
      },
      {
        "href": "/support/what-to-save",
        "label": "Understand the two private codes"
      }
    ]
  },
  {
    "id": "help.getting-started.values-seed",
    "slug": "values-seed",
    "title": "The values seed and your first action",
    "category": "Getting started",
    "categoryId": "getting-started",
    "summary": "Answer seven short questions to choose a starting point; there are no right or wrong answers.",
    "body": [
      "The values seed is the last part of account setup. It asks seven short questions about what matters to you. There are no right or wrong answers, and it is not a test.",
      "Your answers give your new profile a starting point for the topics shown on AgoraNet. They do not create a public personality label, affect another profile, or become a score shared across the platform.",
      "Answer each question in your own words, then select the control to finish account setup. When setup is complete, AgoraNet returns you to the page you originally tried to use or opens your dashboard."
    ],
    "keywords": [
      "values seed",
      "seven questions",
      "first action",
      "orientation"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/verify",
        "label": "Continue account setup"
      }
    ]
  },
  {
    "id": "help.getting-started.verify-once",
    "slug": "verify-once",
    "title": "Why AgoraNet asks you to verify",
    "category": "Getting started",
    "categoryId": "getting-started",
    "summary": "Anyone can read basic onboarding help; creating a profile and participating requires one human-verification check.",
    "body": [
      "You can read AgoraNet's account-creation and onboarding help without signing in. To create a profile or participate by posting, voting, or joining a group, start on the account setup page.",
      "During setup, AgoraNet asks you to complete one human-verification check. When it succeeds, the site shows a one-time private code called a Humanity Credential. It proves that one person completed verification. Save it immediately. AgoraNet cannot display or recover it later.",
      "Next, you create your True Self, which is your public AgoraNet profile. That profile receives a separate access key used to sign in. Save both codes somewhere private and reliable, and never send either code to Support."
    ],
    "keywords": [
      "verify once",
      "why verify",
      "create account",
      "proof of humanity"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate"
    ],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/verify",
        "label": "Start or continue account setup"
      },
      {
        "href": "/constitution",
        "label": "Read the platform constitution"
      }
    ]
  },
  {
    "id": "help.getting-started.what-to-save",
    "slug": "what-to-save",
    "title": "Save your Humanity Credential and access key",
    "category": "Getting started",
    "categoryId": "getting-started",
    "summary": "Account setup shows two different private codes once; learn what each one does and what to do if one is missing.",
    "body": [
      "Account setup gives you two different private codes. AgoraNet stores only protected fingerprints of them, not readable copies. Support therefore cannot display, resend, or reset either code.",
      "The Humanity Credential proves that you completed the one-person verification check. You may need it later to create your private Alias profile. An access key belongs to one specific profile and is what you paste on the Sign in page to use that profile in a new browser.",
      "Save each code as soon as it appears, label it clearly, and keep it out of screenshots, messages, and support requests. If you lose an access key, you cannot sign that profile into another browser. If you lose the Humanity Credential, profiles that are already signed in can still work, but actions requiring that credential may not be available."
    ],
    "keywords": [
      "save access key",
      "save code",
      "humanity credential",
      "login code",
      "where is my key"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/login",
        "label": "Sign in with an access key"
      },
      {
        "href": "/verify",
        "label": "Return to account setup"
      }
    ]
  },
  {
    "id": "help.identities.lost-keys",
    "slug": "lost-keys",
    "title": "Lost keys and recovery boundaries",
    "category": "Your two identities",
    "categoryId": "identities",
    "summary": "AgoraNet cannot resend private sign-in codes; protect any browser that is still signed in and get help if a code may be exposed.",
    "body": [
      "AgoraNet cannot read, resend, or reset a Humanity Credential or profile access key because it does not store a readable copy. Support cannot recover one for you.",
      "If one browser is still signed in, leave that session open. Do not clear its cookies, remove its site data, or sign out while you decide what to do. An Alias, which is a separate private profile, cannot be recovered through the public True Self profile because that would reveal a connection AgoraNet is designed not to store.",
      "If someone else may have seen or copied a code, stop pasting or using that code and open an urgent support request. Describe what happened without including the code itself. Support can help document and assess the problem, but cannot promise to undo actions that are already final."
    ],
    "keywords": [
      "lost key",
      "lost credential",
      "seed phrase",
      "recover account",
      "compromised",
      "stolen wallet"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "critical",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "owners-guide"
    ],
    "documentType": "recovery-boundary",
    "escalateWhen": "A key may be compromised, funds may be at risk, or you are unsure whether an existing signed-in session can be preserved.",
    "links": [
      {
        "href": "/login",
        "label": "Sign in if you still have the access key"
      },
      {
        "href": "/support",
        "label": "Open Help and Support"
      }
    ]
  },
  {
    "id": "help.identities.switching-identities",
    "slug": "switching-identities",
    "title": "Switch between your public and private profiles",
    "category": "Your two identities",
    "categoryId": "identities",
    "summary": "Add each profile to the browser once, then choose which profile is active from the profile button.",
    "body": [
      "Your True Self is your public profile. Your Alias is a separate private profile. Each has its own access key. Open Sign in and add each profile to this browser once.",
      "After both profiles are added, select the round profile button at the bottom-right of AgoraNet. Choose the profile you want to use. The selected name and page colors show which profile is currently active.",
      "Check the active profile before posting, voting, joining a Circle, or sending a message. Changing profiles also closes any feature session that belonged to the previous profile."
    ],
    "keywords": [
      "switch profile",
      "change account",
      "use alias",
      "profile button"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "owners-guide"
    ],
    "documentType": "procedure",
    "links": [
      {
        "href": "/login",
        "label": "Sign in an identity"
      }
    ]
  },
  {
    "id": "help.identities.two-identities",
    "slug": "two-identities",
    "title": "Understand your True Self and Alias",
    "category": "Your two identities",
    "categoryId": "identities",
    "summary": "Your True Self is public and your Alias is separate and private; AgoraNet does not store a link between them.",
    "body": [
      "Your True Self is the public profile you create during account setup. It has a public name and @handle. You can also create one Alias: a separate profile for conversations you do not want connected to your public name.",
      "AgoraNet checks that each verified person creates no more than one Alias without saving which True Self owns it. The database, public record, and search do not contain a link between the two profiles. Creating the Alias therefore asks for your Humanity Credential instead of using your public profile as proof.",
      "A new Alias starts hidden from other users until you choose to make it visible. It receives its own access key, which you must save. The profile name and page colors help show whether you are currently using your True Self or Alias."
    ],
    "keywords": [
      "public profile",
      "private profile",
      "alias",
      "true self",
      "anonymous account"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/alias",
        "label": "Create or manage your Alias"
      }
    ]
  },
  {
    "id": "help.platform-features.circles",
    "slug": "circles",
    "title": "Find and join a Circle",
    "category": "Using AgoraNet",
    "categoryId": "platform-features",
    "summary": "A Circle is a group for working on a shared goal; its main page is public while its member workspace is private to members.",
    "body": [
      "A Circle is an AgoraNet group organized around a shared goal, project, or local problem. Open Browse Circles to search by place or topic, then select a Circle to read its public page.",
      "If the Circle is accepting members, use the Join control on its page. The Circle's member workspace is visible only to members and does not appear in public search.",
      "Your currently selected profile is the profile that joins, leaves, offers help, or completes an action. Check the profile name before selecting a control. An attestation is simply another member's recorded confirmation that an action happened."
    ],
    "keywords": [
      "circle",
      "join circle",
      "members room",
      "place",
      "initiative"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/circles",
        "label": "Browse Circles"
      }
    ]
  },
  {
    "id": "help.platform-features.discussions",
    "slug": "discussions",
    "title": "Discussions, replies, and sources",
    "category": "Using AgoraNet",
    "categoryId": "platform-features",
    "summary": "Read public conversations, start a topic, reply, and check whether a post can be deleted before publishing.",
    "body": [
      "Discussions are AgoraNet's public conversation threads. Open Browse Discussions to read them. To start a topic or reply, you must be signed in with a verified profile.",
      "Before selecting Publish, look for the permanence notice. It tells you whether you can delete your own post later or whether it will remain in the Public Record.",
      "When you refer to an outside source, add its web address in the source field. AgoraNet keeps that address with the post so readers can inspect it and search can find other public conversations citing the same source."
    ],
    "keywords": [
      "post",
      "reply",
      "discussion",
      "citation",
      "source",
      "permanent"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/discussions",
        "label": "Browse Discussions"
      }
    ]
  },
  {
    "id": "help.platform-features.fellow-souls-dms",
    "slug": "fellow-souls-dms",
    "title": "Connections and private messages",
    "category": "Using AgoraNet",
    "categoryId": "platform-features",
    "summary": "“Fellow souls” are profile connections; requests and direct messages stay with the profile that sent or received them.",
    "body": [
      "AgoraNet calls profile connections “fellow souls.” Open Fellow souls & messages to view requests, accepted connections, blocked profiles, and private message threads.",
      "Connections and messages belong only to the profile currently in use. A connection or message on your True Self does not appear on your Alias, and private messages do not appear in public search.",
      "A first message to someone who is not connected to you begins as a request and may show a small published platform fee before you send it. A recipient can report the relevant part of an unsafe message for review; reporting does not make the rest of the conversation public."
    ],
    "keywords": [
      "friend",
      "fellow soul",
      "dm",
      "message",
      "connection request",
      "inbox"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/souls",
        "label": "Fellow Souls & Messages"
      }
    ]
  },
  {
    "id": "help.platform-features.polls-voting",
    "slug": "polls-voting",
    "title": "Polls and voting",
    "category": "Using AgoraNet",
    "categoryId": "platform-features",
    "summary": "Open a poll to read its choices, cost, closing method, and result visibility before you vote.",
    "body": [
      "Open Polls & Governance and select a poll to read its question, choices, closing rule, and any participation fee. You must be signed in with a verified profile to vote.",
      "Each verified person receives the voting influence allowed by that poll. A fee is only a cost to participate; paying more does not buy a stronger vote.",
      "Some polls hide the running total until voting ends. A “candle close” means the exact closing moment is selected from a stated time window, which discourages last-second manipulation. The poll page shows these rules before you submit your vote."
    ],
    "keywords": [
      "poll",
      "vote",
      "ballot",
      "sealed tally",
      "candle close",
      "vote fee"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/governance",
        "label": "Polls & Governance"
      }
    ]
  },
  {
    "id": "help.platform-features.search",
    "slug": "search",
    "title": "Search AgoraNet",
    "category": "Using AgoraNet",
    "categoryId": "platform-features",
    "summary": "Use one search box for public posts, people, groups, polls, sources, records, and Help Center articles.",
    "body": [
      "Open Search, type ordinary words, a name, or an @handle, and submit the search. Results may include public Discussions and replies, Circle and Chamber pages, people, your own connections, places, AgoraNet topic pages, public records, polls, cited websites, and Help Center articles.",
      "Results are ordered by a published formula using how closely they match and public information such as participation and citations. AgoraNet does not reorder results from what you read, how long you look, or what you previously selected. The same words produce the same ordering for everyone.",
      "If you are signed in, your search history belongs only to the profile currently in use. You can delete one search or all history, and history is never used to rank results. Private messages, private member workspaces, hidden moderator information, and anything connecting a True Self to an Alias are never searchable."
    ],
    "keywords": [
      "find something",
      "search people",
      "search help",
      "search history",
      "private search"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "feed-search-spec",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/search",
        "label": "Search"
      },
      {
        "href": "/search/about",
        "label": "How results are ranked"
      },
      {
        "href": "/search/history",
        "label": "Your search history"
      }
    ]
  },
  {
    "id": "help.platform-features.your-feed",
    "slug": "your-feed",
    "title": "Choose what appears in your feed",
    "category": "Using AgoraNet",
    "categoryId": "platform-features",
    "summary": "Your feed contains only the topics, conversations, and groups you select; AgoraNet does not infer interests from your behavior.",
    "body": [
      "Your feed shows updates only from sources you chose, such as AgoraNet topics, Discussions, Circles, Chambers, and polls. Open Choose what feeds it, select or clear the checkboxes you want, and save your sources.",
      "AgoraNet does not add items because you viewed, paused on, or clicked similar content. If you did not select a source, that source cannot enter your personal feed.",
      "Feed choices belong only to the profile currently in use. Your True Self and Alias keep separate lists. People who are not signed in see a general public stream ordered by the same published formula for everyone."
    ],
    "keywords": [
      "change feed",
      "follow topic",
      "feed settings",
      "why is this in my feed"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "feed-search-spec",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/feed/sources",
        "label": "Choose what feeds you"
      }
    ]
  },
  {
    "id": "help.privacy-safety.moderation-appeals",
    "slug": "moderation-appeals",
    "title": "Moderation review and appeals",
    "category": "Privacy, safety & rules",
    "categoryId": "privacy-safety",
    "summary": "Use the Appeal control on the moderation case; Support can help if that control is missing or broken.",
    "body": [
      "If AgoraNet moderated your content or profile, open the moderation notice or case and look for its Appeal control. The notice shows the reason, applicable rule, and any appeal deadline.",
      "Submit the appeal through that control so it stays attached to the correct decision. The AI helpdesk and support operators can explain the process, but they cannot approve an appeal or change a moderation decision.",
      "If the Appeal control is missing, fails before the deadline, or does not accept your submission, open a support request immediately. Include the non-secret case reference and error message, but do not copy private messages or credentials into the request."
    ],
    "keywords": [
      "moderation",
      "appeal",
      "strike",
      "ruling",
      "case"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "high",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "platform-constitution",
      "moderation-spec",
      "owners-guide"
    ],
    "documentType": "procedure",
    "escalateWhen": "The appeal control is unavailable or technically fails before its deadline.",
    "links": [
      {
        "href": "/rules",
        "label": "The rulebook"
      }
    ]
  },
  {
    "id": "help.privacy-safety.permanence",
    "slug": "permanence",
    "title": "Know whether a post can be deleted",
    "category": "Privacy, safety & rules",
    "categoryId": "privacy-safety",
    "summary": "AgoraNet tells you before publishing whether your post is permanent or can later be removed by you.",
    "body": [
      "AgoraNet has two kinds of public posting spaces. In an author-deletable space, you can remove your own post later. In a permanent space, the post enters the Public Record and cannot be edited or deleted by you, Support, or the platform.",
      "Before you publish, look for the amber permanence notice near the posting control. It appears with the same color on every profile so it is easier to recognize. Read it before selecting Publish.",
      "Changing a display name later does not rewrite the name recorded with an earlier permanent post. If you are unsure or do not want the words kept permanently, do not publish in that space."
    ],
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "platform-constitution",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/record",
        "label": "The Public Record"
      }
    ]
  },
  {
    "id": "help.privacy-safety.privacy-profile-boundaries",
    "slug": "privacy-profile-boundaries",
    "title": "Privacy and profile boundaries",
    "category": "Privacy, safety & rules",
    "categoryId": "privacy-safety",
    "summary": "Support sees only the profile used for the request and never uses your help questions to rank or judge you.",
    "body": [
      "When you ask for help while signed in, the question or support request belongs to the profile currently selected in your browser. Support does not search for, guess, or reveal whether that profile has another identity.",
      "Your help questions are not used to change your Light Score, feed, search results, moderation treatment, or standing on the platform. Light Score is AgoraNet's public contribution indicator; contacting Support does not affect it.",
      "The helpdesk receives only limited technical context, such as the current page or account-setup step, a non-secret error code, and the web-app version. Never add an access key, Humanity Credential, wallet secret, password, or unrelated private information."
    ],
    "keywords": [
      "privacy",
      "alias link",
      "cross persona",
      "support history",
      "search history"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "high",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "platform-constitution",
      "owners-guide"
    ],
    "documentType": "concept",
    "links": [
      {
        "href": "/support",
        "label": "Open Help and Support"
      }
    ]
  },
  {
    "id": "help.privacy-safety.report-content",
    "slug": "report-content",
    "title": "Report content or behavior",
    "category": "Privacy, safety & rules",
    "categoryId": "privacy-safety",
    "summary": "Use the Report control beside the content so reviewers receive the correct item; contact Support if reporting is unavailable or safety is urgent.",
    "body": [
      "To report a post, reply, profile, or private message, open the item and select its Report control. Reporting from the item gives reviewers the correct reference and only the evidence needed for review.",
      "Choose the closest reason, add only the context the form asks for, and submit it. Do not repost harmful or private material in a public Discussion to explain the problem.",
      "If someone may be in immediate danger, private information is exposed, an account may be compromised, or the Report control does not work, open a high-priority support request. AgoraNet Support is not an emergency service; contact local emergency services when immediate real-world help is needed."
    ],
    "keywords": [
      "report",
      "harassment",
      "abuse",
      "unsafe",
      "flag",
      "moderation"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "high",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "platform-constitution",
      "moderation-spec",
      "owners-guide"
    ],
    "documentType": "procedure",
    "escalateWhen": "There is a safety threat, privacy exposure, account compromise, or the normal report path is unavailable.",
    "links": [
      {
        "href": "/rules",
        "label": "Read the moderation rules"
      }
    ]
  },
  {
    "id": "help.troubleshooting.browser-technical-help",
    "slug": "browser-technical-help",
    "title": "Browser and connection troubleshooting",
    "category": "Troubleshooting",
    "categoryId": "troubleshooting",
    "summary": "Try a short set of safe checks without accidentally losing the only browser session that can access your profile.",
    "body": [
      "First, check whether another website loads. Then return to AgoraNet, refresh the page once, and try the same action one more time. If a button opened a wallet window, unlock the wallet and check that no approval is waiting behind the browser.",
      "Do not clear cookies, remove AgoraNet site data, use a browser-cleaning tool, or sign out if you do not have the profile's access key. The current browser may be the only place where that profile is still available.",
      "If the page still fails, open Help and Support. State which page you were on, what you selected, what you expected, and the exact non-secret error message. Do not include an access key, Humanity Credential, wallet seed phrase, private key, or password."
    ],
    "keywords": [
      "page not loading",
      "technical help",
      "browser error",
      "session",
      "stuck",
      "network error"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "troubleshooting",
    "escalateWhen": "The same action fails twice, the page cannot load, or clearing local state could strand an identity.",
    "links": [
      {
        "href": "/support",
        "label": "Ask the helpdesk or open a request"
      }
    ]
  },
  {
    "id": "help.troubleshooting.contact-support",
    "slug": "contact-support",
    "title": "Open a support request",
    "category": "Troubleshooting",
    "categoryId": "troubleshooting",
    "summary": "Open Help and Support, describe the problem in ordinary words, and keep private codes out of the request.",
    "body": [
      "Open Help and Support. You can ask the AI helpdesk in your own words, or select “Skip self-service and open a support request” to contact a human operator.",
      "For a support request, state what you were trying to do, which page you were on, what happened, and any error message that does not contain a secret. Check screenshots before attaching or sharing them. Remove access keys, Humanity Credentials, wallet seed phrases, private messages, passwords, and unrelated personal information.",
      "After submission, AgoraNet shows a case reference beginning with AN-. Save that reference. Signed-out users must provide a reply email; signed-in requests stay with the currently selected profile. Support can investigate and explain, but separate authorized processes decide verification, moderation, security, treasury, and other consequential changes."
    ],
    "keywords": [
      "contact support",
      "support ticket",
      "help request",
      "human",
      "case"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "procedure",
    "escalateWhen": "Self-service did not resolve the issue or any high-risk condition applies.",
    "links": [
      {
        "href": "/support",
        "label": "Open Help and Support"
      }
    ]
  },
  {
    "id": "help.troubleshooting.known-issues",
    "slug": "known-issues",
    "title": "Known problems and service status",
    "category": "Troubleshooting",
    "categoryId": "troubleshooting",
    "summary": "Check whether AgoraNet has already identified a problem affecting multiple users.",
    "body": [
      "AgoraNet publishes a known-issue notice when the same technical problem affects multiple users. Each notice names the affected feature, when the problem was first seen, any safe workaround, and whether it has been resolved.",
      "No active incident is listed in this version. If the same action keeps failing, ask the helpdesk or open a support request so the operator can compare it with other reports."
    ],
    "keywords": [
      "known issue",
      "outage",
      "status",
      "down",
      "service unavailable"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "known-issue",
    "links": [
      {
        "href": "/support",
        "label": "Ask about a problem or report one"
      }
    ]
  },
  {
    "id": "help.troubleshooting.transaction-pending",
    "slug": "transaction-pending",
    "title": "A transaction is pending or failed",
    "category": "Troubleshooting",
    "categoryId": "troubleshooting",
    "summary": "Check the wallet status and test network, save the public transaction reference, and avoid sending the same transaction repeatedly.",
    "body": [
      "Open the wallet used for the action. Check whether it shows the transaction as pending, failed, rejected, or confirmed, and confirm that the wallet is using the same Cardano test network shown by AgoraNet.",
      "Pending means the test network has not confirmed the transaction yet. Rejected means the wallet did not submit it. Confirmed means the network accepted it, although AgoraNet may need additional time to display the result.",
      "Save the transaction hash, which is the public reference shown by the wallet. If there is no hash, save the non-secret error message and the action you attempted. Do not submit the same value-moving action repeatedly. Open a support request if a confirmed transaction is missing, the balance is unexpected, or you are unsure whether retrying would duplicate it."
    ],
    "keywords": [
      "transaction pending",
      "transaction failed",
      "tx hash",
      "chain",
      "balance missing"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "high",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "economy-specs",
      "owners-guide"
    ],
    "documentType": "troubleshooting",
    "escalateWhen": "A confirmed transaction is not reflected, the balance is unexpected, or repeated attempts could duplicate the action.",
    "links": [
      {
        "href": "/transparency",
        "label": "Check published transaction information"
      },
      {
        "href": "/support",
        "label": "Open Help and Support"
      }
    ]
  },
  {
    "id": "help.troubleshooting.verification-troubleshooting",
    "slug": "verification-troubleshooting",
    "title": "Verification is pending, rejected, or interrupted",
    "category": "Troubleshooting",
    "categoryId": "troubleshooting",
    "summary": "Return to account setup in the same browser, save the non-secret error message, and request human review after a repeated failure or rejection.",
    "body": [
      "Open the account setup page again in the same browser. Refreshing or closing a tab does not create a second profile. AgoraNet should continue from the last completed setup step.",
      "If the page reports an error, note the heading shown on the page, what you selected, and the non-secret error code. Try the same safe step only once more. Never send Support a Humanity Credential, access key, wallet seed phrase, private key, or password.",
      "If verification is rejected, remains pending, or the same step fails twice, open a support request. The AI helpdesk cannot change a verification decision; a human operator must review the safe diagnostic record."
    ],
    "keywords": [
      "verification failed",
      "verification pending",
      "stuck onboarding",
      "issuer",
      "proof of humanity"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate"
    ],
    "version": "1.2.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "high",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ],
    "documentType": "troubleshooting",
    "escalateWhen": "The same verification step fails twice, the issuer reports a rejection, or you suspect your credential was exposed.",
    "links": [
      {
        "href": "/verify",
        "label": "Open onboarding"
      }
    ]
  },
  {
    "id": "help.troubleshooting.wallet-connection",
    "slug": "wallet-connection",
    "title": "Wallet connection troubleshooting",
    "category": "Troubleshooting",
    "categoryId": "troubleshooting",
    "summary": "Unlock Lace, select the test network shown by AgoraNet, reload once, and approve the browser connection.",
    "body": [
      "AgoraNet's current wallet features use a Cardano test network, not Cardano mainnet. Confirm that the Lace browser wallet is installed and unlocked. In Lace, select the same test network named on the AgoraNet page.",
      "Return to AgoraNet, reload the page once, select Connect wallet, and approve the request in the Lace window. If no wallet window appears, check whether the browser blocked a pop-up or whether the Lace window opened behind another window.",
      "If it still does not connect, open Help and Support and include the browser name, selected network, and non-secret error message. A public wallet address or transaction hash may be included when needed. Never include a seed phrase, spending password, signing key, private key, or access key."
    ],
    "keywords": [
      "wallet not connecting",
      "Lace",
      "CIP-30",
      "preprod",
      "wrong network",
      "wallet error"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "version": "1.1.0",
    "updatedAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "owner": "support-content",
    "risk": "normal",
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "documentType": "troubleshooting",
    "escalateWhen": "The wallet remains unavailable after reload, the network is correct, and the wallet itself shows no pending approval.",
    "links": [
      {
        "href": "/support",
        "label": "Open Help and Support"
      }
    ]
  }
] as const;
export const GENERATED_HELP_RETRIEVAL_DOCUMENTS = [
  {
    "id": "help.economy.donations-treasury",
    "slug": "donations-treasury",
    "title": "Donations and the treasury",
    "summary": "Check published treasury activity and distinguish AgoraNet balances from test-network wallet transactions.",
    "text": "Open Transparency for published fees and system activity. Open Treasury for public treasury balances and transactions. AgoraNet labels an internal platform balance separately from a Cardano test-network wallet transaction so you can tell which system you are looking at.\n\nIf a donation or treasury transaction looks missing, first check whether your wallet shows it as pending, failed, or confirmed. Save the transaction hash, which is the public reference shown by the wallet, and note the approximate time.\n\nDo not retry a value-moving action repeatedly, and never send Support a wallet seed phrase, spending password, private key, or signing key. A confirmed transaction that is missing from AgoraNet, an unexpected balance change, or suspected theft requires a human support request.",
    "audience": "public",
    "categoryId": "economy",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "donation",
      "treasury",
      "balance",
      "funds",
      "transaction",
      "dPOLL"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "economy-specs",
      "owners-guide"
    ],
    "escalateWhen": "A confirmed transaction is absent from the platform, a balance changed unexpectedly, or compromise is suspected."
  },
  {
    "id": "help.economy.money",
    "slug": "money",
    "title": "PollCoin, Gratium, and platform fees",
    "summary": "Learn what AgoraNet's two internal balances do, why small fees exist, and where to check the current amounts.",
    "text": "AgoraNet uses two internal balances. PollCoin, shown as PC, pays platform participation fees and deposits. Gratium, shown as G, records appreciation. A new profile receives a starting amount of each so it can take its first actions.\n\nSmall fees and refundable deposits discourage automated spam and repeated disruptive actions. A fee is not vote weight, reputation, or permission to break a rule. Current amounts and limits are published on Transparency and may change through the platform's approved voting process.\n\nAgoraNet does not sell or rank attention. Views, time spent reading, and engagement tracking are not used to build a personal advertising profile or to decide what appears in search.",
    "audience": "public",
    "categoryId": "economy",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "PollCoin",
      "Gratium",
      "PC",
      "fee",
      "balance",
      "cost"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "economy-specs",
      "owners-guide"
    ]
  },
  {
    "id": "help.getting-started.onboarding-interrupted",
    "slug": "onboarding-interrupted",
    "title": "Onboarding was interrupted",
    "summary": "Reopen account setup in the same browser, or sign in if you already created a profile and saved its access key.",
    "text": "Open the account setup page in the same browser you used before. AgoraNet will carry forward any completed setup step. You do not need to remember the page's internal name, and Support will never ask you to reconstruct or share a private code that was shown once.\n\nIf you already created a profile and saved its access key, open Sign in instead of beginning again. If an access key appeared but you did not save it, do not create another profile or send any private code to Support. Read “Save your Humanity Credential and access key” before taking another action.",
    "audience": "public",
    "categoryId": "getting-started",
    "documentType": "troubleshooting",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "onboarding stuck",
      "continue onboarding",
      "closed browser",
      "resume",
      "start over"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate",
      "credential",
      "identity",
      "alias",
      "values"
    ],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.getting-started.values-seed",
    "slug": "values-seed",
    "title": "The values seed and your first action",
    "summary": "Answer seven short questions to choose a starting point; there are no right or wrong answers.",
    "text": "The values seed is the last part of account setup. It asks seven short questions about what matters to you. There are no right or wrong answers, and it is not a test.\n\nYour answers give your new profile a starting point for the topics shown on AgoraNet. They do not create a public personality label, affect another profile, or become a score shared across the platform.\n\nAnswer each question in your own words, then select the control to finish account setup. When setup is complete, AgoraNet returns you to the page you originally tried to use or opens your dashboard.",
    "audience": "public",
    "categoryId": "getting-started",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "values seed",
      "seven questions",
      "first action",
      "orientation"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.getting-started.verify-once",
    "slug": "verify-once",
    "title": "Why AgoraNet asks you to verify",
    "summary": "Anyone can read basic onboarding help; creating a profile and participating requires one human-verification check.",
    "text": "You can read AgoraNet's account-creation and onboarding help without signing in. To create a profile or participate by posting, voting, or joining a group, start on the account setup page.\n\nDuring setup, AgoraNet asks you to complete one human-verification check. When it succeeds, the site shows a one-time private code called a Humanity Credential. It proves that one person completed verification. Save it immediately. AgoraNet cannot display or recover it later.\n\nNext, you create your True Self, which is your public AgoraNet profile. That profile receives a separate access key used to sign in. Save both codes somewhere private and reliable, and never send either code to Support.",
    "audience": "public",
    "categoryId": "getting-started",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "verify once",
      "why verify",
      "create account",
      "proof of humanity"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate"
    ],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.getting-started.what-to-save",
    "slug": "what-to-save",
    "title": "Save your Humanity Credential and access key",
    "summary": "Account setup shows two different private codes once; learn what each one does and what to do if one is missing.",
    "text": "Account setup gives you two different private codes. AgoraNet stores only protected fingerprints of them, not readable copies. Support therefore cannot display, resend, or reset either code.\n\nThe Humanity Credential proves that you completed the one-person verification check. You may need it later to create your private Alias profile. An access key belongs to one specific profile and is what you paste on the Sign in page to use that profile in a new browser.\n\nSave each code as soon as it appears, label it clearly, and keep it out of screenshots, messages, and support requests. If you lose an access key, you cannot sign that profile into another browser. If you lose the Humanity Credential, profiles that are already signed in can still work, but actions requiring that credential may not be available.",
    "audience": "public",
    "categoryId": "getting-started",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "save access key",
      "save code",
      "humanity credential",
      "login code",
      "where is my key"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.identities.lost-keys",
    "slug": "lost-keys",
    "title": "Lost keys and recovery boundaries",
    "summary": "AgoraNet cannot resend private sign-in codes; protect any browser that is still signed in and get help if a code may be exposed.",
    "text": "AgoraNet cannot read, resend, or reset a Humanity Credential or profile access key because it does not store a readable copy. Support cannot recover one for you.\n\nIf one browser is still signed in, leave that session open. Do not clear its cookies, remove its site data, or sign out while you decide what to do. An Alias, which is a separate private profile, cannot be recovered through the public True Self profile because that would reveal a connection AgoraNet is designed not to store.\n\nIf someone else may have seen or copied a code, stop pasting or using that code and open an urgent support request. Describe what happened without including the code itself. Support can help document and assess the problem, but cannot promise to undo actions that are already final.",
    "audience": "public",
    "categoryId": "identities",
    "documentType": "recovery-boundary",
    "risk": "critical",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "lost key",
      "lost credential",
      "seed phrase",
      "recover account",
      "compromised",
      "stolen wallet"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "owners-guide"
    ],
    "escalateWhen": "A key may be compromised, funds may be at risk, or you are unsure whether an existing signed-in session can be preserved."
  },
  {
    "id": "help.identities.switching-identities",
    "slug": "switching-identities",
    "title": "Switch between your public and private profiles",
    "summary": "Add each profile to the browser once, then choose which profile is active from the profile button.",
    "text": "Your True Self is your public profile. Your Alias is a separate private profile. Each has its own access key. Open Sign in and add each profile to this browser once.\n\nAfter both profiles are added, select the round profile button at the bottom-right of AgoraNet. Choose the profile you want to use. The selected name and page colors show which profile is currently active.\n\nCheck the active profile before posting, voting, joining a Circle, or sending a message. Changing profiles also closes any feature session that belonged to the previous profile.",
    "audience": "public",
    "categoryId": "identities",
    "documentType": "procedure",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "switch profile",
      "change account",
      "use alias",
      "profile button"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.identities.two-identities",
    "slug": "two-identities",
    "title": "Understand your True Self and Alias",
    "summary": "Your True Self is public and your Alias is separate and private; AgoraNet does not store a link between them.",
    "text": "Your True Self is the public profile you create during account setup. It has a public name and @handle. You can also create one Alias: a separate profile for conversations you do not want connected to your public name.\n\nAgoraNet checks that each verified person creates no more than one Alias without saving which True Self owns it. The database, public record, and search do not contain a link between the two profiles. Creating the Alias therefore asks for your Humanity Credential instead of using your public profile as proof.\n\nA new Alias starts hidden from other users until you choose to make it visible. It receives its own access key, which you must save. The profile name and page colors help show whether you are currently using your True Self or Alias.",
    "audience": "public",
    "categoryId": "identities",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "public profile",
      "private profile",
      "alias",
      "true self",
      "anonymous account"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.platform-features.circles",
    "slug": "circles",
    "title": "Find and join a Circle",
    "summary": "A Circle is a group for working on a shared goal; its main page is public while its member workspace is private to members.",
    "text": "A Circle is an AgoraNet group organized around a shared goal, project, or local problem. Open Browse Circles to search by place or topic, then select a Circle to read its public page.\n\nIf the Circle is accepting members, use the Join control on its page. The Circle's member workspace is visible only to members and does not appear in public search.\n\nYour currently selected profile is the profile that joins, leaves, offers help, or completes an action. Check the profile name before selecting a control. An attestation is simply another member's recorded confirmation that an action happened.",
    "audience": "public",
    "categoryId": "platform-features",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "circle",
      "join circle",
      "members room",
      "place",
      "initiative"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ]
  },
  {
    "id": "help.platform-features.discussions",
    "slug": "discussions",
    "title": "Discussions, replies, and sources",
    "summary": "Read public conversations, start a topic, reply, and check whether a post can be deleted before publishing.",
    "text": "Discussions are AgoraNet's public conversation threads. Open Browse Discussions to read them. To start a topic or reply, you must be signed in with a verified profile.\n\nBefore selecting Publish, look for the permanence notice. It tells you whether you can delete your own post later or whether it will remain in the Public Record.\n\nWhen you refer to an outside source, add its web address in the source field. AgoraNet keeps that address with the post so readers can inspect it and search can find other public conversations citing the same source.",
    "audience": "public",
    "categoryId": "platform-features",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "post",
      "reply",
      "discussion",
      "citation",
      "source",
      "permanent"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ]
  },
  {
    "id": "help.platform-features.fellow-souls-dms",
    "slug": "fellow-souls-dms",
    "title": "Connections and private messages",
    "summary": "“Fellow souls” are profile connections; requests and direct messages stay with the profile that sent or received them.",
    "text": "AgoraNet calls profile connections “fellow souls.” Open Fellow souls & messages to view requests, accepted connections, blocked profiles, and private message threads.\n\nConnections and messages belong only to the profile currently in use. A connection or message on your True Self does not appear on your Alias, and private messages do not appear in public search.\n\nA first message to someone who is not connected to you begins as a request and may show a small published platform fee before you send it. A recipient can report the relevant part of an unsafe message for review; reporting does not make the rest of the conversation public.",
    "audience": "public",
    "categoryId": "platform-features",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "friend",
      "fellow soul",
      "dm",
      "message",
      "connection request",
      "inbox"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ]
  },
  {
    "id": "help.platform-features.polls-voting",
    "slug": "polls-voting",
    "title": "Polls and voting",
    "summary": "Open a poll to read its choices, cost, closing method, and result visibility before you vote.",
    "text": "Open Polls & Governance and select a poll to read its question, choices, closing rule, and any participation fee. You must be signed in with a verified profile to vote.\n\nEach verified person receives the voting influence allowed by that poll. A fee is only a cost to participate; paying more does not buy a stronger vote.\n\nSome polls hide the running total until voting ends. A “candle close” means the exact closing moment is selected from a stated time window, which discourages last-second manipulation. The poll page shows these rules before you submit your vote.",
    "audience": "public",
    "categoryId": "platform-features",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "poll",
      "vote",
      "ballot",
      "sealed tally",
      "candle close",
      "vote fee"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ]
  },
  {
    "id": "help.platform-features.search",
    "slug": "search",
    "title": "Search AgoraNet",
    "summary": "Use one search box for public posts, people, groups, polls, sources, records, and Help Center articles.",
    "text": "Open Search, type ordinary words, a name, or an @handle, and submit the search. Results may include public Discussions and replies, Circle and Chamber pages, people, your own connections, places, AgoraNet topic pages, public records, polls, cited websites, and Help Center articles.\n\nResults are ordered by a published formula using how closely they match and public information such as participation and citations. AgoraNet does not reorder results from what you read, how long you look, or what you previously selected. The same words produce the same ordering for everyone.\n\nIf you are signed in, your search history belongs only to the profile currently in use. You can delete one search or all history, and history is never used to rank results. Private messages, private member workspaces, hidden moderator information, and anything connecting a True Self to an Alias are never searchable.",
    "audience": "public",
    "categoryId": "platform-features",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "find something",
      "search people",
      "search help",
      "search history",
      "private search"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "feed-search-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.platform-features.your-feed",
    "slug": "your-feed",
    "title": "Choose what appears in your feed",
    "summary": "Your feed contains only the topics, conversations, and groups you select; AgoraNet does not infer interests from your behavior.",
    "text": "Your feed shows updates only from sources you chose, such as AgoraNet topics, Discussions, Circles, Chambers, and polls. Open Choose what feeds it, select or clear the checkboxes you want, and save your sources.\n\nAgoraNet does not add items because you viewed, paused on, or clicked similar content. If you did not select a source, that source cannot enter your personal feed.\n\nFeed choices belong only to the profile currently in use. Your True Self and Alias keep separate lists. People who are not signed in see a general public stream ordered by the same published formula for everyone.",
    "audience": "public",
    "categoryId": "platform-features",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "change feed",
      "follow topic",
      "feed settings",
      "why is this in my feed"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "feed-search-spec",
      "owners-guide"
    ]
  },
  {
    "id": "help.privacy-safety.moderation-appeals",
    "slug": "moderation-appeals",
    "title": "Moderation review and appeals",
    "summary": "Use the Appeal control on the moderation case; Support can help if that control is missing or broken.",
    "text": "If AgoraNet moderated your content or profile, open the moderation notice or case and look for its Appeal control. The notice shows the reason, applicable rule, and any appeal deadline.\n\nSubmit the appeal through that control so it stays attached to the correct decision. The AI helpdesk and support operators can explain the process, but they cannot approve an appeal or change a moderation decision.\n\nIf the Appeal control is missing, fails before the deadline, or does not accept your submission, open a support request immediately. Include the non-secret case reference and error message, but do not copy private messages or credentials into the request.",
    "audience": "public",
    "categoryId": "privacy-safety",
    "documentType": "procedure",
    "risk": "high",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "moderation",
      "appeal",
      "strike",
      "ruling",
      "case"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "platform-constitution",
      "moderation-spec",
      "owners-guide"
    ],
    "escalateWhen": "The appeal control is unavailable or technically fails before its deadline."
  },
  {
    "id": "help.privacy-safety.permanence",
    "slug": "permanence",
    "title": "Know whether a post can be deleted",
    "summary": "AgoraNet tells you before publishing whether your post is permanent or can later be removed by you.",
    "text": "AgoraNet has two kinds of public posting spaces. In an author-deletable space, you can remove your own post later. In a permanent space, the post enters the Public Record and cannot be edited or deleted by you, Support, or the platform.\n\nBefore you publish, look for the amber permanence notice near the posting control. It appears with the same color on every profile so it is easier to recognize. Read it before selecting Publish.\n\nChanging a display name later does not rewrite the name recorded with an earlier permanent post. If you are unsure or do not want the words kept permanently, do not publish in that space.",
    "audience": "public",
    "categoryId": "privacy-safety",
    "documentType": "concept",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "platform-constitution",
      "owners-guide"
    ]
  },
  {
    "id": "help.privacy-safety.privacy-profile-boundaries",
    "slug": "privacy-profile-boundaries",
    "title": "Privacy and profile boundaries",
    "summary": "Support sees only the profile used for the request and never uses your help questions to rank or judge you.",
    "text": "When you ask for help while signed in, the question or support request belongs to the profile currently selected in your browser. Support does not search for, guess, or reveal whether that profile has another identity.\n\nYour help questions are not used to change your Light Score, feed, search results, moderation treatment, or standing on the platform. Light Score is AgoraNet's public contribution indicator; contacting Support does not affect it.\n\nThe helpdesk receives only limited technical context, such as the current page or account-setup step, a non-secret error code, and the web-app version. Never add an access key, Humanity Credential, wallet secret, password, or unrelated private information.",
    "audience": "public",
    "categoryId": "privacy-safety",
    "documentType": "concept",
    "risk": "high",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "privacy",
      "alias link",
      "cross persona",
      "support history",
      "search history"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "dual-identity-spec",
      "platform-constitution",
      "owners-guide"
    ]
  },
  {
    "id": "help.privacy-safety.report-content",
    "slug": "report-content",
    "title": "Report content or behavior",
    "summary": "Use the Report control beside the content so reviewers receive the correct item; contact Support if reporting is unavailable or safety is urgent.",
    "text": "To report a post, reply, profile, or private message, open the item and select its Report control. Reporting from the item gives reviewers the correct reference and only the evidence needed for review.\n\nChoose the closest reason, add only the context the form asks for, and submit it. Do not repost harmful or private material in a public Discussion to explain the problem.\n\nIf someone may be in immediate danger, private information is exposed, an account may be compromised, or the Report control does not work, open a high-priority support request. AgoraNet Support is not an emergency service; contact local emergency services when immediate real-world help is needed.",
    "audience": "public",
    "categoryId": "privacy-safety",
    "documentType": "procedure",
    "risk": "high",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "report",
      "harassment",
      "abuse",
      "unsafe",
      "flag",
      "moderation"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "platform-constitution",
      "moderation-spec",
      "owners-guide"
    ],
    "escalateWhen": "There is a safety threat, privacy exposure, account compromise, or the normal report path is unavailable."
  },
  {
    "id": "help.troubleshooting.browser-technical-help",
    "slug": "browser-technical-help",
    "title": "Browser and connection troubleshooting",
    "summary": "Try a short set of safe checks without accidentally losing the only browser session that can access your profile.",
    "text": "First, check whether another website loads. Then return to AgoraNet, refresh the page once, and try the same action one more time. If a button opened a wallet window, unlock the wallet and check that no approval is waiting behind the browser.\n\nDo not clear cookies, remove AgoraNet site data, use a browser-cleaning tool, or sign out if you do not have the profile's access key. The current browser may be the only place where that profile is still available.\n\nIf the page still fails, open Help and Support. State which page you were on, what you selected, what you expected, and the exact non-secret error message. Do not include an access key, Humanity Credential, wallet seed phrase, private key, or password.",
    "audience": "public",
    "categoryId": "troubleshooting",
    "documentType": "troubleshooting",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "page not loading",
      "technical help",
      "browser error",
      "session",
      "stuck",
      "network error"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "escalateWhen": "The same action fails twice, the page cannot load, or clearing local state could strand an identity."
  },
  {
    "id": "help.troubleshooting.contact-support",
    "slug": "contact-support",
    "title": "Open a support request",
    "summary": "Open Help and Support, describe the problem in ordinary words, and keep private codes out of the request.",
    "text": "Open Help and Support. You can ask the AI helpdesk in your own words, or select “Skip self-service and open a support request” to contact a human operator.\n\nFor a support request, state what you were trying to do, which page you were on, what happened, and any error message that does not contain a secret. Check screenshots before attaching or sharing them. Remove access keys, Humanity Credentials, wallet seed phrases, private messages, passwords, and unrelated personal information.\n\nAfter submission, AgoraNet shows a case reference beginning with AN-. Save that reference. Signed-out users must provide a reply email; signed-in requests stay with the currently selected profile. Support can investigate and explain, but separate authorized processes decide verification, moderation, security, treasury, and other consequential changes.",
    "audience": "public",
    "categoryId": "troubleshooting",
    "documentType": "procedure",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "contact support",
      "support ticket",
      "help request",
      "human",
      "case"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "escalateWhen": "Self-service did not resolve the issue or any high-risk condition applies."
  },
  {
    "id": "help.troubleshooting.known-issues",
    "slug": "known-issues",
    "title": "Known problems and service status",
    "summary": "Check whether AgoraNet has already identified a problem affecting multiple users.",
    "text": "AgoraNet publishes a known-issue notice when the same technical problem affects multiple users. Each notice names the affected feature, when the problem was first seen, any safe workaround, and whether it has been resolved.\n\nNo active incident is listed in this version. If the same action keeps failing, ask the helpdesk or open a support request so the operator can compare it with other reports.",
    "audience": "public",
    "categoryId": "troubleshooting",
    "documentType": "known-issue",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "known issue",
      "outage",
      "status",
      "down",
      "service unavailable"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ]
  },
  {
    "id": "help.troubleshooting.transaction-pending",
    "slug": "transaction-pending",
    "title": "A transaction is pending or failed",
    "summary": "Check the wallet status and test network, save the public transaction reference, and avoid sending the same transaction repeatedly.",
    "text": "Open the wallet used for the action. Check whether it shows the transaction as pending, failed, rejected, or confirmed, and confirm that the wallet is using the same Cardano test network shown by AgoraNet.\n\nPending means the test network has not confirmed the transaction yet. Rejected means the wallet did not submit it. Confirmed means the network accepted it, although AgoraNet may need additional time to display the result.\n\nSave the transaction hash, which is the public reference shown by the wallet. If there is no hash, save the non-secret error message and the action you attempted. Do not submit the same value-moving action repeatedly. Open a support request if a confirmed transaction is missing, the balance is unexpected, or you are unsure whether retrying would duplicate it.",
    "audience": "public",
    "categoryId": "troubleshooting",
    "documentType": "troubleshooting",
    "risk": "high",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "transaction pending",
      "transaction failed",
      "tx hash",
      "chain",
      "balance missing"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "economy-specs",
      "owners-guide"
    ],
    "escalateWhen": "A confirmed transaction is not reflected, the balance is unexpected, or repeated attempts could duplicate the action."
  },
  {
    "id": "help.troubleshooting.verification-troubleshooting",
    "slug": "verification-troubleshooting",
    "title": "Verification is pending, rejected, or interrupted",
    "summary": "Return to account setup in the same browser, save the non-secret error message, and request human review after a repeated failure or rejection.",
    "text": "Open the account setup page again in the same browser. Refreshing or closing a tab does not create a second profile. AgoraNet should continue from the last completed setup step.\n\nIf the page reports an error, note the heading shown on the page, what you selected, and the non-secret error code. Try the same safe step only once more. Never send Support a Humanity Credential, access key, wallet seed phrase, private key, or password.\n\nIf verification is rejected, remains pending, or the same step fails twice, open a support request. The AI helpdesk cannot change a verification decision; a human operator must review the safe diagnostic record.",
    "audience": "public",
    "categoryId": "troubleshooting",
    "documentType": "troubleshooting",
    "risk": "high",
    "version": "1.2.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "verification failed",
      "verification pending",
      "stuck onboarding",
      "issuer",
      "proof of humanity"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate"
    ],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "onboarding-spec",
      "owners-guide"
    ],
    "escalateWhen": "The same verification step fails twice, the issuer reports a rejection, or you suspect your credential was exposed."
  },
  {
    "id": "help.troubleshooting.wallet-connection",
    "slug": "wallet-connection",
    "title": "Wallet connection troubleshooting",
    "summary": "Unlock Lace, select the test network shown by AgoraNet, reload once, and approve the browser connection.",
    "text": "AgoraNet's current wallet features use a Cardano test network, not Cardano mainnet. Confirm that the Lace browser wallet is installed and unlocked. In Lace, select the same test network named on the AgoraNet page.\n\nReturn to AgoraNet, reload the page once, select Connect wallet, and approve the request in the Lace window. If no wallet window appears, check whether the browser blocked a pop-up or whether the Lace window opened behind another window.\n\nIf it still does not connect, open Help and Support and include the browser name, selected network, and non-secret error message. A public wallet address or transaction hash may be included when needed. Never include a seed phrase, spending password, signing key, private key, or access key.",
    "audience": "public",
    "categoryId": "troubleshooting",
    "documentType": "troubleshooting",
    "risk": "normal",
    "version": "1.1.0",
    "effectiveAt": "2026-08-22",
    "reviewBy": "2027-02-23",
    "keywords": [
      "wallet not connecting",
      "Lace",
      "CIP-30",
      "preprod",
      "wrong network",
      "wallet error"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owner-directive-2026-07-21",
      "owners-guide"
    ],
    "escalateWhen": "The wallet remains unavailable after reload, the network is correct, and the wallet itself shows no pending approval."
  },
  {
    "id": "internal.capability.current",
    "title": "Current helpdesk capability matrix",
    "summary": "Distinguishes implemented support functions from planned or unavailable functions.",
    "text": "Implemented: public Help Center, twenty-five approved public articles, help search, contextual onboarding links, deterministic grounded guidance, grounded model-generated answers from the protected Gemma testnet runtime, secret rejection, support-case creation, rate limits, an internal command-line case queue, and a restricted browser-based operator console.\n\nModel generation uses only application-selected approved evidence and must fall back safely to deterministic guidance when the protected runtime is unavailable.\n\nNot implemented: account or secret recovery, automatic transaction reversal, verification-decision changes, moderation-decision changes, automatic email delivery, a staffed response-time promise, and an in-product support inbox for end users.\n\nNever claim that a planned or simulated capability is available in the deployed product.",
    "audience": "operator",
    "categoryId": "platform-features",
    "documentType": "capability-matrix",
    "risk": "high",
    "version": "1.1.0",
    "effectiveAt": "2026-08-23",
    "reviewBy": "2026-11-23",
    "keywords": [
      "capability",
      "implemented",
      "unavailable",
      "support operations"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "owners-guide"
    ],
    "escalateWhen": "A request depends on a capability not listed as implemented."
  },
  {
    "id": "internal.errors.core",
    "title": "Core support error-handling catalog",
    "summary": "Defines how unregistered error codes and repeatable failures are handled safely.",
    "text": "Only codes explicitly registered in this corpus may be interpreted. An unfamiliar code is recorded as safe diagnostic context; the helpdesk must not infer its meaning from its name.\n\nFor an unregistered code, capture only the page address, visible page heading or account-setup step, client version, timestamp, and code. Ask for those items in ordinary words; do not require the user to know an internal stage name. Do not request screenshots or copied text that may contain credentials or private information unless an approved procedure defines the evidence boundary.\n\nIf the same safe step fails twice, offer a human support request and preserve the non-secret code. Consequential categories use the deterministic severity floor.",
    "audience": "operator",
    "categoryId": "troubleshooting",
    "documentType": "error-catalog",
    "risk": "high",
    "version": "1.1.0",
    "effectiveAt": "2026-08-23",
    "reviewBy": "2026-11-23",
    "keywords": [
      "error code",
      "repeatable failure",
      "diagnostics"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate",
      "credential",
      "identity",
      "alias",
      "values"
    ],
    "sourceRefs": [
      "help-support-spec",
      "owners-guide"
    ],
    "escalateWhen": "An error repeats after the approved safe step, blocks onboarding, or could involve identity, funds, privacy, or security."
  },
  {
    "id": "internal.escalation.core",
    "title": "Core helpdesk escalation matrix",
    "summary": "Establishes severity floors and the boundary between self-service and human review.",
    "text": "Critical: active compromise, reported security vulnerability, exposed private data, or potentially missing funds. Stop self-service and route for urgent human review without promising a response time that operations has not ratified.\n\nHigh: repeated onboarding blockage, verification review, lost keys, privacy or harassment concerns, moderation appeals, and suspected compromise without an active-loss signal.\n\nNormal: repeatable feature malfunction, pending transaction, or technical failure that remains unresolved after approved safe steps.\n\nInformational: supported how-to and policy questions. The model may raise severity but never reduce the deterministic application classification.\n\nUser-facing escalation language must state what the person should select in Help and Support, what non-secret information to include, and what Support can and cannot do. Do not answer only with an internal severity label.",
    "audience": "operator",
    "categoryId": "privacy-safety",
    "documentType": "escalation-matrix",
    "risk": "critical",
    "version": "1.1.0",
    "effectiveAt": "2026-08-23",
    "reviewBy": "2026-11-23",
    "keywords": [
      "escalation",
      "severity",
      "compromise",
      "missing funds",
      "verification",
      "moderation"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "dual-identity-spec",
      "moderation-spec"
    ],
    "escalateWhen": "Any mandatory category below is detected."
  },
  {
    "id": "internal.troubleshooting.onboarding",
    "title": "Onboarding troubleshooting tree",
    "summary": "Provides a bounded sequence for interrupted or repeatedly failing onboarding.",
    "text": "First identify the current account-setup step from allowlisted context or ask one focused question about the heading visible on the page. Do not expect the user to know an internal stage name. Do not ask the user to repeat a completed verification check or recreate a profile until the approved article establishes that it is safe.\n\nIf the browser was closed, send the user to the account setup page at `/verify` and ask them to open it in the same browser. If a profile was already created and its access key was saved, send them to Sign in at `/login` instead of telling them to begin again.\n\nIf a one-time secret was shown but may not have been saved, stop and apply the recovery-boundary guidance. If verification was rejected or the same step fails twice, offer a human support request with the stage and non-secret error code.",
    "audience": "operator",
    "categoryId": "getting-started",
    "documentType": "troubleshooting-tree",
    "risk": "high",
    "version": "1.2.0",
    "effectiveAt": "2026-08-23",
    "reviewBy": "2026-11-23",
    "keywords": [
      "onboarding stuck",
      "verification failed",
      "resume",
      "gate"
    ],
    "errorCodes": [],
    "onboardingStages": [
      "gate",
      "credential",
      "identity",
      "alias",
      "values"
    ],
    "sourceRefs": [
      "help-support-spec",
      "onboarding-spec",
      "dual-identity-spec"
    ],
    "escalateWhen": "The same stage fails twice, verification needs review, or a one-time secret may be lost or exposed."
  },
  {
    "id": "policy.support.boundaries",
    "title": "Approved helpdesk authority and privacy boundaries",
    "summary": "Defines the non-negotiable limits on helpdesk knowledge, identity handling, secrets, and actions.",
    "text": "The helpdesk explains approved AgoraNet behavior and safe procedures. It does not change identity, verification, funds, moderation, recovery, privacy, or on-chain state.\n\nSupport information remains scoped to the active profile. Convenience never justifies correlating True Self and Alias. Private messages, members-room interiors, hidden moderation signals, and another profile's history are unavailable unless a separately approved, consented, role-gated procedure explicitly permits the minimum necessary evidence.\n\nThe helpdesk never requests or retains credentials, access keys, passwords, wallet seed phrases, private keys, signing keys, or authentication secrets. It does not promise recovery or reversal where AgoraNet holds no such capability.\n\nSafety boundaries must be explained in language a first-time user can act on. When a safe destination exists, name the visible page or control and the information the user may provide. Internal terminology must never become a barrier to receiving help.",
    "audience": "operator",
    "categoryId": "privacy-safety",
    "documentType": "policy",
    "risk": "critical",
    "version": "1.1.0",
    "effectiveAt": "2026-08-23",
    "reviewBy": "2026-11-23",
    "keywords": [
      "authority",
      "privacy",
      "secrets",
      "dual identity",
      "recovery"
    ],
    "errorCodes": [],
    "onboardingStages": [],
    "sourceRefs": [
      "help-support-spec",
      "platform-constitution",
      "dual-identity-spec",
      "moderation-spec"
    ],
    "escalateWhen": "A request would exceed helpdesk authority or weaken identity, privacy, moderation, recovery, or financial safeguards."
  }
] as const;
